/* Generated by Yosys 0.38 (git sha1 4964457dc, gcc 11.2.1 -fPIC -Os) */

module I_DELAY_primitive_inst(reset, in, DLY_LOAD, DLY_ADJ, DLY_INCDEC, DLY_TAP_VALUE, CLK_IN, O);
  input CLK_IN;
  input DLY_ADJ;
  input DLY_INCDEC;
  input DLY_LOAD;
  output [5:0] DLY_TAP_VALUE;
  output O;
  input in;
  input reset;
  wire \$auto_440 ;
  wire \$auto_441 ;
  wire \$auto_442 ;
  wire \$auto_443 ;
  wire \$auto_444 ;
  wire \$auto_445 ;
  wire \$auto_446 ;
  wire \$auto_447 ;
  wire \$auto_448 ;
  wire \$auto_449 ;
  wire \$auto_450 ;
  wire \$auto_451 ;
  wire \$auto_452 ;
  wire \$auto_453 ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:10.9-10.15" *)
  wire \$auto_454.CLK_IN ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:7.9-7.16" *)
  wire \$auto_454.DLY_ADJ ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:8.9-8.19" *)
  wire \$auto_454.DLY_INCDEC ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:6.9-6.17" *)
  wire \$auto_454.DLY_LOAD ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire [5:0] \$auto_454.DLY_TAP_VALUE ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:11.10-11.11" *)
  wire \$auto_454.O ;
  (* init = 1'h0 *)
  (* keep = 32'sd1 *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:14.5-14.8" *)
  wire \$auto_454.dff ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:5.9-5.11" *)
  wire \$auto_454.in ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:4.9-4.14" *)
  wire \$auto_454.reset ;
  wire \$clk_buf_$ibuf_CLK_IN ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:7.9-7.16" *)
  wire \$f2g_trx_dly_adj_$ibuf_DLY_ADJ ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:8.9-8.19" *)
  wire \$f2g_trx_dly_inc_$ibuf_DLY_INCDEC ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:6.9-6.17" *)
  wire \$f2g_trx_dly_ld_$ibuf_DLY_LOAD ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$f2g_tx_out_$obuf_DLY_TAP_VALUE[0] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$f2g_tx_out_$obuf_DLY_TAP_VALUE[1] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$f2g_tx_out_$obuf_DLY_TAP_VALUE[2] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$f2g_tx_out_$obuf_DLY_TAP_VALUE[3] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$f2g_tx_out_$obuf_DLY_TAP_VALUE[4] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$f2g_tx_out_$obuf_DLY_TAP_VALUE[5] ;
  wire \$flatten$auto_454.$auto_440 ;
  wire \$flatten$auto_454.$auto_441 ;
  wire \$flatten$auto_454.$auto_442 ;
  wire \$flatten$auto_454.$auto_443 ;
  wire \$flatten$auto_454.$auto_444 ;
  wire \$flatten$auto_454.$auto_445 ;
  wire \$flatten$auto_454.$auto_446 ;
  wire \$flatten$auto_454.$auto_447 ;
  wire \$flatten$auto_454.$auto_448 ;
  wire \$flatten$auto_454.$auto_449 ;
  wire \$flatten$auto_454.$auto_450 ;
  wire \$flatten$auto_454.$auto_451 ;
  wire \$flatten$auto_454.$auto_452 ;
  wire \$flatten$auto_454.$auto_453 ;
  wire \$flatten$auto_454.$clk_buf_$ibuf_CLK_IN ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:7.9-7.16" *)
  wire \$flatten$auto_454.$f2g_trx_dly_adj_$ibuf_DLY_ADJ ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:8.9-8.19" *)
  wire \$flatten$auto_454.$f2g_trx_dly_inc_$ibuf_DLY_INCDEC ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:6.9-6.17" *)
  wire \$flatten$auto_454.$f2g_trx_dly_ld_$ibuf_DLY_LOAD ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$f2g_tx_out_$obuf_DLY_TAP_VALUE[0] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$f2g_tx_out_$obuf_DLY_TAP_VALUE[1] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$f2g_tx_out_$obuf_DLY_TAP_VALUE[2] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$f2g_tx_out_$obuf_DLY_TAP_VALUE[3] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$f2g_tx_out_$obuf_DLY_TAP_VALUE[4] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$f2g_tx_out_$obuf_DLY_TAP_VALUE[5] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:10.9-10.15" *)
  wire \$flatten$auto_454.$ibuf_CLK_IN ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:7.9-7.16" *)
  wire \$flatten$auto_454.$ibuf_DLY_ADJ ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:8.9-8.19" *)
  wire \$flatten$auto_454.$ibuf_DLY_INCDEC ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:6.9-6.17" *)
  wire \$flatten$auto_454.$ibuf_DLY_LOAD ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:5.9-5.11" *)
  wire \$flatten$auto_454.$ibuf_in ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:4.9-4.14" *)
  wire \$flatten$auto_454.$ibuf_reset ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$ifab_$obuf_DLY_TAP_VALUE[0] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$ifab_$obuf_DLY_TAP_VALUE[1] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$ifab_$obuf_DLY_TAP_VALUE[2] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$ifab_$obuf_DLY_TAP_VALUE[3] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$ifab_$obuf_DLY_TAP_VALUE[4] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$flatten$auto_454.$ifab_$obuf_DLY_TAP_VALUE[5] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:11.10-11.11" *)
  wire \$flatten$auto_454.$obuf_O ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:10.9-10.15" *)
  wire \$ibuf_CLK_IN ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:7.9-7.16" *)
  wire \$ibuf_DLY_ADJ ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:8.9-8.19" *)
  wire \$ibuf_DLY_INCDEC ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:6.9-6.17" *)
  wire \$ibuf_DLY_LOAD ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:5.9-5.11" *)
  wire \$ibuf_in ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:4.9-4.14" *)
  wire \$ibuf_reset ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$ifab_$obuf_DLY_TAP_VALUE[0] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$ifab_$obuf_DLY_TAP_VALUE[1] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$ifab_$obuf_DLY_TAP_VALUE[2] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$ifab_$obuf_DLY_TAP_VALUE[3] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$ifab_$obuf_DLY_TAP_VALUE[4] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire \$ifab_$obuf_DLY_TAP_VALUE[5] ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:11.10-11.11" *)
  wire \$obuf_O ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:10.9-10.15" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:10.9-10.15" *)
  wire CLK_IN;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:7.9-7.16" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:7.9-7.16" *)
  wire DLY_ADJ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:8.9-8.19" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:8.9-8.19" *)
  wire DLY_INCDEC;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:6.9-6.17" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:6.9-6.17" *)
  wire DLY_LOAD;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:9.16-9.29" *)
  wire [5:0] DLY_TAP_VALUE;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:11.10-11.11" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:11.10-11.11" *)
  wire O;
  (* init = 1'h0 *)
  (* keep = 32'sd1 *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:14.5-14.8" *)
  wire dff;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:5.9-5.11" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:5.9-5.11" *)
  wire in;
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:4.9-4.14" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:4.9-4.14" *)
  wire reset;
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RS_FPGA_PRIMITIVES_new/I_DELAY_primitive_inst/./rtl/I_DELAY_primitive_inst.v:18.3-26.2" *)
  I_DELAY #(
    .DELAY(32'sd0)
  ) \$auto_454.inst  (
    .CLK_IN(\$clk_buf_$ibuf_CLK_IN ),
    .DLY_ADJ(\$f2g_trx_dly_adj_$ibuf_DLY_ADJ ),
    .DLY_INCDEC(\$f2g_trx_dly_inc_$ibuf_DLY_INCDEC ),
    .DLY_LOAD(\$f2g_trx_dly_ld_$ibuf_DLY_LOAD ),
    .DLY_TAP_VALUE({ \$ifab_$obuf_DLY_TAP_VALUE[5] , \$ifab_$obuf_DLY_TAP_VALUE[4] , \$ifab_$obuf_DLY_TAP_VALUE[3] , \$ifab_$obuf_DLY_TAP_VALUE[2] , \$ifab_$obuf_DLY_TAP_VALUE[1] , \$ifab_$obuf_DLY_TAP_VALUE[0]  }),
    .I(dff),
    .O(\$obuf_O )
  );
  (* keep = 32'sd1 *)
  CLK_BUF \$flatten$auto_454.$clkbuf$I_DELAY_primitive_inst.$ibuf_CLK_IN  (
    .I(\$flatten$auto_454.$ibuf_CLK_IN ),
    .O(\$clk_buf_$ibuf_CLK_IN )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto_454.$ibuf$I_DELAY_primitive_inst.$ibuf_CLK_IN  (
    .EN(\$auto_440 ),
    .I(CLK_IN),
    .O(\$flatten$auto_454.$ibuf_CLK_IN )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto_454.$ibuf$I_DELAY_primitive_inst.$ibuf_DLY_ADJ  (
    .EN(\$auto_441 ),
    .I(DLY_ADJ),
    .O(\$ibuf_DLY_ADJ )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto_454.$ibuf$I_DELAY_primitive_inst.$ibuf_DLY_INCDEC  (
    .EN(\$auto_442 ),
    .I(DLY_INCDEC),
    .O(\$ibuf_DLY_INCDEC )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto_454.$ibuf$I_DELAY_primitive_inst.$ibuf_DLY_LOAD  (
    .EN(\$auto_443 ),
    .I(DLY_LOAD),
    .O(\$ibuf_DLY_LOAD )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto_454.$ibuf$I_DELAY_primitive_inst.$ibuf_in  (
    .EN(\$auto_444 ),
    .I(in),
    .O(\$ibuf_in )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto_454.$ibuf$I_DELAY_primitive_inst.$ibuf_reset  (
    .EN(\$auto_445 ),
    .I(reset),
    .O(\$ibuf_reset )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUFT \$flatten$auto_454.$obuf$I_DELAY_primitive_inst.$obuf_DLY_TAP_VALUE  (
    .I(\$f2g_tx_out_$obuf_DLY_TAP_VALUE[0] ),
    .O(DLY_TAP_VALUE[0]),
    .T(\$auto_446 )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUFT \$flatten$auto_454.$obuf$I_DELAY_primitive_inst.$obuf_DLY_TAP_VALUE_1  (
    .I(\$f2g_tx_out_$obuf_DLY_TAP_VALUE[1] ),
    .O(DLY_TAP_VALUE[1]),
    .T(\$auto_447 )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUFT \$flatten$auto_454.$obuf$I_DELAY_primitive_inst.$obuf_DLY_TAP_VALUE_2  (
    .I(\$f2g_tx_out_$obuf_DLY_TAP_VALUE[2] ),
    .O(DLY_TAP_VALUE[2]),
    .T(\$auto_448 )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUFT \$flatten$auto_454.$obuf$I_DELAY_primitive_inst.$obuf_DLY_TAP_VALUE_3  (
    .I(\$f2g_tx_out_$obuf_DLY_TAP_VALUE[3] ),
    .O(DLY_TAP_VALUE[3]),
    .T(\$auto_449 )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUFT \$flatten$auto_454.$obuf$I_DELAY_primitive_inst.$obuf_DLY_TAP_VALUE_4  (
    .I(\$f2g_tx_out_$obuf_DLY_TAP_VALUE[4] ),
    .O(DLY_TAP_VALUE[4]),
    .T(\$auto_450 )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUFT \$flatten$auto_454.$obuf$I_DELAY_primitive_inst.$obuf_DLY_TAP_VALUE_5  (
    .I(\$f2g_tx_out_$obuf_DLY_TAP_VALUE[5] ),
    .O(DLY_TAP_VALUE[5]),
    .T(\$auto_451 )
  );
  (* keep = 32'sd1 *)
  (* module_not_derived = 32'sd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_19_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUFT \$flatten$auto_454.$obuf$I_DELAY_primitive_inst.$obuf_O  (
    .I(\$auto_453 ),
    .O(O),
    .T(\$auto_452 )
  );
  fabric_I_DELAY_primitive_inst fabric_instance (
    .\$auto_440 (\$auto_440 ),
    .\$auto_441 (\$auto_441 ),
    .\$auto_442 (\$auto_442 ),
    .\$auto_443 (\$auto_443 ),
    .\$auto_444 (\$auto_444 ),
    .\$auto_445 (\$auto_445 ),
    .\$auto_446 (\$auto_446 ),
    .\$auto_447 (\$auto_447 ),
    .\$auto_448 (\$auto_448 ),
    .\$auto_449 (\$auto_449 ),
    .\$auto_450 (\$auto_450 ),
    .\$auto_451 (\$auto_451 ),
    .\$auto_452 (\$auto_452 ),
    .\$auto_453 (\$auto_453 ),
    .\$clk_buf_$ibuf_CLK_IN (\$clk_buf_$ibuf_CLK_IN ),
    .\$f2g_trx_dly_adj_$ibuf_DLY_ADJ (\$f2g_trx_dly_adj_$ibuf_DLY_ADJ ),
    .\$f2g_trx_dly_inc_$ibuf_DLY_INCDEC (\$f2g_trx_dly_inc_$ibuf_DLY_INCDEC ),
    .\$f2g_trx_dly_ld_$ibuf_DLY_LOAD (\$f2g_trx_dly_ld_$ibuf_DLY_LOAD ),
    .\$f2g_tx_out_$obuf_DLY_TAP_VALUE[0] (\$f2g_tx_out_$obuf_DLY_TAP_VALUE[0] ),
    .\$f2g_tx_out_$obuf_DLY_TAP_VALUE[1] (\$f2g_tx_out_$obuf_DLY_TAP_VALUE[1] ),
    .\$f2g_tx_out_$obuf_DLY_TAP_VALUE[2] (\$f2g_tx_out_$obuf_DLY_TAP_VALUE[2] ),
    .\$f2g_tx_out_$obuf_DLY_TAP_VALUE[3] (\$f2g_tx_out_$obuf_DLY_TAP_VALUE[3] ),
    .\$f2g_tx_out_$obuf_DLY_TAP_VALUE[4] (\$f2g_tx_out_$obuf_DLY_TAP_VALUE[4] ),
    .\$f2g_tx_out_$obuf_DLY_TAP_VALUE[5] (\$f2g_tx_out_$obuf_DLY_TAP_VALUE[5] ),
    .\$ibuf_DLY_ADJ (\$ibuf_DLY_ADJ ),
    .\$ibuf_DLY_INCDEC (\$ibuf_DLY_INCDEC ),
    .\$ibuf_DLY_LOAD (\$ibuf_DLY_LOAD ),
    .\$ibuf_in (\$ibuf_in ),
    .\$ibuf_reset (\$ibuf_reset ),
    .\$ifab_$obuf_DLY_TAP_VALUE[0] (\$ifab_$obuf_DLY_TAP_VALUE[0] ),
    .\$ifab_$obuf_DLY_TAP_VALUE[1] (\$ifab_$obuf_DLY_TAP_VALUE[1] ),
    .\$ifab_$obuf_DLY_TAP_VALUE[2] (\$ifab_$obuf_DLY_TAP_VALUE[2] ),
    .\$ifab_$obuf_DLY_TAP_VALUE[3] (\$ifab_$obuf_DLY_TAP_VALUE[3] ),
    .\$ifab_$obuf_DLY_TAP_VALUE[4] (\$ifab_$obuf_DLY_TAP_VALUE[4] ),
    .\$ifab_$obuf_DLY_TAP_VALUE[5] (\$ifab_$obuf_DLY_TAP_VALUE[5] ),
    .\$obuf_O (\$obuf_O ),
    .dff(dff)
  );
endmodule
