-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/02_12_2023_09_15_01/share/raptor/sim_models/rapidsilicon/genesis2/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir .././ ../ /nfs_project/castor/DV/Hamza/RS/Raptor-Bashing/mult/. 
-vlog-libdir .././ 
-vlog-libext .v
-vlog-libext .sv
-vlog-define 
-vlog2k /nfs_project/castor/DV/Hamza/RS/Raptor-Bashing/mult/./mult.v
-top mult
