-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/01_26_2023_09_15_01/share/raptor/sim_models/rapidsilicon/genesis2/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir .././ 
-vlog-libdir .././ 
-vlog-libext .v
-vlog-libext .sv
-vlog-define 
-vlog2k /nfs_project/castor/DV/Hamza/RS/Castor_Fabric_10x8/Castor_V2/DV/fabric/uvm_fabric_verif_env/src/Designs/benchmarks/dsp/mac_32_arst/./mac_32_arst.v
-top mac_32_arst
