-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/05_14_2023_15_30_00/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir ../ /nfs_project/castor/DV/Azfar/phew 
-vlog-libdir 
-vlog-define 
-vlog2k /nfs_project/castor/DV/Azfar/phew/up_down_counter.v
-top up_down_counter
