/* Generated by Yosys 0.38 (git sha1 6c475f1f1, gcc 11.2.1 -fPIC -Os) */

module GJC4_updated(a, b, feedback, unsigned_a, unsigned_b, z_mult);
  input [19:0] a;
  input [17:0] b;
  input [2:0] feedback;
  input unsigned_a;
  input unsigned_b;
  output [37:0] z_mult;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire [19:0] a;
  wire [17:0] b;
  wire [2:0] feedback;
  wire unsigned_a;
  wire unsigned_b;
  wire [37:0] z_mult;
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _081_ (
    .EN(1'b1),
    .I(a[0]),
    .O(_000_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _082_ (
    .EN(1'b1),
    .I(a[1]),
    .O(_011_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _083_ (
    .EN(1'b1),
    .I(a[10]),
    .O(_001_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _084_ (
    .EN(1'b1),
    .I(a[11]),
    .O(_002_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _085_ (
    .EN(1'b1),
    .I(a[12]),
    .O(_003_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _086_ (
    .EN(1'b1),
    .I(a[13]),
    .O(_004_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _087_ (
    .EN(1'b1),
    .I(a[14]),
    .O(_005_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _088_ (
    .EN(1'b1),
    .I(a[15]),
    .O(_006_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _089_ (
    .EN(1'b1),
    .I(a[16]),
    .O(_007_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _090_ (
    .EN(1'b1),
    .I(a[17]),
    .O(_008_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _091_ (
    .EN(1'b1),
    .I(a[18]),
    .O(_009_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _092_ (
    .EN(1'b1),
    .I(a[19]),
    .O(_010_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _093_ (
    .EN(1'b1),
    .I(a[2]),
    .O(_012_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _094_ (
    .EN(1'b1),
    .I(a[3]),
    .O(_013_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _095_ (
    .EN(1'b1),
    .I(a[4]),
    .O(_014_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _096_ (
    .EN(1'b1),
    .I(a[5]),
    .O(_015_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _097_ (
    .EN(1'b1),
    .I(a[6]),
    .O(_016_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _098_ (
    .EN(1'b1),
    .I(a[7]),
    .O(_017_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _099_ (
    .EN(1'b1),
    .I(a[8]),
    .O(_018_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _100_ (
    .EN(1'b1),
    .I(a[9]),
    .O(_019_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _101_ (
    .EN(1'b1),
    .I(b[0]),
    .O(_020_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _102_ (
    .EN(1'b1),
    .I(b[1]),
    .O(_029_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _103_ (
    .EN(1'b1),
    .I(b[10]),
    .O(_021_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _104_ (
    .EN(1'b1),
    .I(b[11]),
    .O(_022_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _105_ (
    .EN(1'b1),
    .I(b[12]),
    .O(_023_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _106_ (
    .EN(1'b1),
    .I(b[13]),
    .O(_024_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _107_ (
    .EN(1'b1),
    .I(b[14]),
    .O(_025_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _108_ (
    .EN(1'b1),
    .I(b[15]),
    .O(_026_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _109_ (
    .EN(1'b1),
    .I(b[16]),
    .O(_027_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _110_ (
    .EN(1'b1),
    .I(b[17]),
    .O(_028_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _111_ (
    .EN(1'b1),
    .I(b[2]),
    .O(_030_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _112_ (
    .EN(1'b1),
    .I(b[3]),
    .O(_031_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _113_ (
    .EN(1'b1),
    .I(b[4]),
    .O(_032_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _114_ (
    .EN(1'b1),
    .I(b[5]),
    .O(_033_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _115_ (
    .EN(1'b1),
    .I(b[6]),
    .O(_034_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _116_ (
    .EN(1'b1),
    .I(b[7]),
    .O(_035_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _117_ (
    .EN(1'b1),
    .I(b[8]),
    .O(_036_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _118_ (
    .EN(1'b1),
    .I(b[9]),
    .O(_037_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _119_ (
    .EN(1'b1),
    .I(feedback[0]),
    .O(_038_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _120_ (
    .EN(1'b1),
    .I(feedback[1]),
    .O(_039_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _121_ (
    .EN(1'b1),
    .I(feedback[2]),
    .O(_040_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _122_ (
    .EN(1'b1),
    .I(unsigned_a),
    .O(_041_)
  );
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) _123_ (
    .EN(1'b1),
    .I(unsigned_b),
    .O(_042_)
  );
  O_BUFT _124_ (
    .I(_043_),
    .O(z_mult[0]),
    .T(1'b1)
  );
  O_BUFT _125_ (
    .I(_054_),
    .O(z_mult[1]),
    .T(1'b1)
  );
  O_BUFT _126_ (
    .I(_044_),
    .O(z_mult[10]),
    .T(1'b1)
  );
  O_BUFT _127_ (
    .I(_045_),
    .O(z_mult[11]),
    .T(1'b1)
  );
  O_BUFT _128_ (
    .I(_046_),
    .O(z_mult[12]),
    .T(1'b1)
  );
  O_BUFT _129_ (
    .I(_047_),
    .O(z_mult[13]),
    .T(1'b1)
  );
  O_BUFT _130_ (
    .I(_048_),
    .O(z_mult[14]),
    .T(1'b1)
  );
  O_BUFT _131_ (
    .I(_049_),
    .O(z_mult[15]),
    .T(1'b1)
  );
  O_BUFT _132_ (
    .I(_050_),
    .O(z_mult[16]),
    .T(1'b1)
  );
  O_BUFT _133_ (
    .I(_051_),
    .O(z_mult[17]),
    .T(1'b1)
  );
  O_BUFT _134_ (
    .I(_052_),
    .O(z_mult[18]),
    .T(1'b1)
  );
  O_BUFT _135_ (
    .I(_053_),
    .O(z_mult[19]),
    .T(1'b1)
  );
  O_BUFT _136_ (
    .I(_065_),
    .O(z_mult[2]),
    .T(1'b1)
  );
  O_BUFT _137_ (
    .I(_055_),
    .O(z_mult[20]),
    .T(1'b1)
  );
  O_BUFT _138_ (
    .I(_056_),
    .O(z_mult[21]),
    .T(1'b1)
  );
  O_BUFT _139_ (
    .I(_057_),
    .O(z_mult[22]),
    .T(1'b1)
  );
  O_BUFT _140_ (
    .I(_058_),
    .O(z_mult[23]),
    .T(1'b1)
  );
  O_BUFT _141_ (
    .I(_059_),
    .O(z_mult[24]),
    .T(1'b1)
  );
  O_BUFT _142_ (
    .I(_060_),
    .O(z_mult[25]),
    .T(1'b1)
  );
  O_BUFT _143_ (
    .I(_061_),
    .O(z_mult[26]),
    .T(1'b1)
  );
  O_BUFT _144_ (
    .I(_062_),
    .O(z_mult[27]),
    .T(1'b1)
  );
  O_BUFT _145_ (
    .I(_063_),
    .O(z_mult[28]),
    .T(1'b1)
  );
  O_BUFT _146_ (
    .I(_064_),
    .O(z_mult[29]),
    .T(1'b1)
  );
  O_BUFT _147_ (
    .I(_074_),
    .O(z_mult[3]),
    .T(1'b1)
  );
  O_BUFT _148_ (
    .I(_066_),
    .O(z_mult[30]),
    .T(1'b1)
  );
  O_BUFT _149_ (
    .I(_067_),
    .O(z_mult[31]),
    .T(1'b1)
  );
  O_BUFT _150_ (
    .I(_068_),
    .O(z_mult[32]),
    .T(1'b1)
  );
  O_BUFT _151_ (
    .I(_069_),
    .O(z_mult[33]),
    .T(1'b1)
  );
  O_BUFT _152_ (
    .I(_070_),
    .O(z_mult[34]),
    .T(1'b1)
  );
  O_BUFT _153_ (
    .I(_071_),
    .O(z_mult[35]),
    .T(1'b1)
  );
  O_BUFT _154_ (
    .I(_072_),
    .O(z_mult[36]),
    .T(1'b1)
  );
  O_BUFT _155_ (
    .I(_073_),
    .O(z_mult[37]),
    .T(1'b1)
  );
  O_BUFT _156_ (
    .I(_075_),
    .O(z_mult[4]),
    .T(1'b1)
  );
  O_BUFT _157_ (
    .I(_076_),
    .O(z_mult[5]),
    .T(1'b1)
  );
  O_BUFT _158_ (
    .I(_077_),
    .O(z_mult[6]),
    .T(1'b1)
  );
  O_BUFT _159_ (
    .I(_078_),
    .O(z_mult[7]),
    .T(1'b1)
  );
  O_BUFT _160_ (
    .I(_079_),
    .O(z_mult[8]),
    .T(1'b1)
  );
  O_BUFT _161_ (
    .I(_080_),
    .O(z_mult[9]),
    .T(1'b1)
  );
  DSP38 #(
    .DSP_MODE("MULTIPLY"),
    .INPUT_REG_EN("FALSE"),
    .OUTPUT_REG_EN("FALSE")
  ) dut_mult (
    .A({ _010_, _009_, _008_, _007_, _006_, _005_, _004_, _003_, _002_, _001_, _019_, _018_, _017_, _016_, _015_, _014_, _013_, _012_, _011_, _000_ }),
    .B({ _028_, _027_, _026_, _025_, _024_, _023_, _022_, _021_, _037_, _036_, _035_, _034_, _033_, _032_, _031_, _030_, _029_, _020_ }),
    .FEEDBACK({ _040_, _039_, _038_ }),
    .UNSIGNED_A(_041_),
    .UNSIGNED_B(_042_),
    .Z({ _073_, _072_, _071_, _070_, _069_, _068_, _067_, _066_, _064_, _063_, _062_, _061_, _060_, _059_, _058_, _057_, _056_, _055_, _053_, _052_, _051_, _050_, _049_, _048_, _047_, _046_, _045_, _044_, _080_, _079_, _078_, _077_, _076_, _075_, _074_, _065_, _054_, _043_ })
  );
endmodule
