/* Generated by Yosys 0.18+10 (git sha1 89ed6d12d, gcc 11.2.1 -fPIC -Os) */

module dsp_fractured_accum_output_shifted_rounded(clk, reset, subtract_i, load_acc_i, shift_right_i, round_i, A, B, P);
  output [63:0] P;
  input [8:0] B;
  input reset;
  input round_i;
  input load_acc_i;
  input [5:0] shift_right_i;
  input clk;
  input [9:0] A;
  input subtract_i;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:6.21-6.22" *)
  wire [9:0] \$auto$rs_design_edit.cc:682:execute$41199.A ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:7.21-7.22" *)
  wire [8:0] \$auto$rs_design_edit.cc:682:execute$41199.B ;
  (* keep = 32'd1 *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:8.27-8.28" *)
  wire [63:0] \$auto$rs_design_edit.cc:682:execute$41199.P ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.20-3.30" *)
  wire \$auto$rs_design_edit.cc:682:execute$41199.subtract_i ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.8-3.11" *)
  wire \$auto$rs_design_edit.cc:682:execute$41199.clk ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:4.14-4.27" *)
  wire [5:0] \$auto$rs_design_edit.cc:682:execute$41199.shift_right_i ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$round_i ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:5.8-5.15" *)
  wire \$auto$rs_design_edit.cc:682:execute$41199.round_i ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.13-3.18" *)
  wire \$auto$rs_design_edit.cc:682:execute$41199.reset ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$load_acc_i ;
  wire [5:0] \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$shift_right_i ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$subtract_i ;
  wire [63:0] \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$clk ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$reset ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.32-3.42" *)
  wire \$auto$rs_design_edit.cc:682:execute$41199.load_acc_i ;
  wire [9:0] \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A ;
  wire [8:0] \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$B ;
  wire \$flatten$auto$rs_design_edit.cc:682:execute$41199.$auto$clkbufmap.cc:298:execute$40576 ;
  (* keep = 32'd1 *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:8.27-8.28" *)
  (* keep = 32'd1 *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:8.27-8.28" *)
  wire [63:0] P;
  wire \$iopadmap$subtract_i ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:7.21-7.22" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:7.21-7.22" *)
  wire [8:0] B;
  wire \$iopadmap$load_acc_i ;
  wire \$iopadmap$reset ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.13-3.18" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.13-3.18" *)
  wire reset;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:5.8-5.15" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:5.8-5.15" *)
  wire round_i;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.32-3.42" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.32-3.42" *)
  wire load_acc_i;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:4.14-4.27" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:4.14-4.27" *)
  wire [5:0] shift_right_i;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.8-3.11" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.8-3.11" *)
  wire clk;
  wire [63:0] \$iopadmap$P ;
  wire [8:0] \$iopadmap$B ;
  wire \$auto$clkbufmap.cc:298:execute$40576 ;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:6.21-6.22" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:6.21-6.22" *)
  wire [9:0] A;
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.20-3.30" *)
  (* src = "/nfs_scratch/scratch/CompilerValidation/abdul_hameed/25march/dsp_fractured_accum_output_shifted_rounded/EDA-2663/./rtl/dsp_fractured_accum_output_shifted_rounded.v:3.20-3.30" *)
  wire subtract_i;
  wire [5:0] \$iopadmap$shift_right_i ;
  wire [9:0] \$iopadmap$A ;
  wire \$iopadmap$round_i ;
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_16  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [16]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [16])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_17  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [17]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [17])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_18  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [18]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [18])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_19  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [19]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [19])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_2  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [2]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_20  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [20]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [20])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_21  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [21]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [21])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_22  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [22]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [22])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_23  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [23]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [23])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_24  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [24]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [24])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_25  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [25]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [25])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_26  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [26]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [26])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_27  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [27]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [27])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_28  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [28]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [28])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_29  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [29]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [29])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_3  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [3]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [3])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_30  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [30]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [30])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_31  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [31]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [31])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_32  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [32]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [32])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_33  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [33]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [33])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_34  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [34]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [34])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_35  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [35]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [35])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_36  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [36]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [36])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_37  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [37]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [37])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_38  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [38]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [38])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_39  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [39]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [39])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_4  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [4]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [4])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_40  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [40]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [40])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_41  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [41]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [41])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_42  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [42]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [42])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_43  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [43]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [43])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_44  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [44]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [44])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_45  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [45]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [45])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_46  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [46]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [46])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_47  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [47]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [47])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_48  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [48]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [48])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_49  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [49]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [49])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_5  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [5]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [5])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_50  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [50]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [50])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_51  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [51]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [51])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_52  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [52]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [52])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_53  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [53]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [53])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_54  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [54]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [54])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_55  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [55]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [55])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_56  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [56]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [56])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_57  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [57]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [57])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_58  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [58]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [58])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_59  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [59]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [59])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_6  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [6]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [6])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_60  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [60]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [60])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_61  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [61]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [61])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_62  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [62]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [62])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_63  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [63]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [63])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_7  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [7]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [7])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_8  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [8]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [8])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_9  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [9]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [9])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.clk  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.clk ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$clk )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.load_acc_i  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.load_acc_i ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$load_acc_i )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.reset  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.reset ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$reset )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.round_i  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.round_i ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$round_i )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.shift_right_i  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.shift_right_i [0]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$shift_right_i [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.shift_right_i_1  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.shift_right_i [1]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$shift_right_i [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.shift_right_i_2  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.shift_right_i [2]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$shift_right_i [2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.shift_right_i_3  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.shift_right_i [3]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$shift_right_i [3])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.shift_right_i_4  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.shift_right_i [4]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$shift_right_i [4])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.shift_right_i_5  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.shift_right_i [5]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$shift_right_i [5])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.subtract_i  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.subtract_i ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$subtract_i )
  );
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:14.13-14.45" *)
  CLK_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$auto$clkbufmap.cc:265:execute$40574  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$clk ),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$auto$clkbufmap.cc:298:execute$40576 )
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.A  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.A [0]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.A_1  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.A [1]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.A_2  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.A [2]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A [2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.A_3  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.A [3]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A [3])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.A_4  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.A [4]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A [4])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.A_5  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.A [5]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A [5])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.A_6  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.A [6]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A [6])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.A_7  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.A [7]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A [7])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.A_8  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.A [8]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A [8])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.A_9  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.A [9]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A [9])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.B  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.B [0]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$B [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.B_1  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.B [1]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$B [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.B_2  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.B [2]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$B [2])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.B_3  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.B [3]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$B [3])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.B_4  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.B [4]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$B [4])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.B_5  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.B [5]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$B [5])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.B_6  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.B [6]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$B [6])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.B_7  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.B [7]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$B [7])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:29.41-29.81" *)
  I_BUF #(
    .WEAK_KEEPER("NONE")
  ) \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.B_8  (
    .EN(1'h1),
    .I(\$auto$rs_design_edit.cc:682:execute$41199.B [8]),
    .O(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$B [8])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [0]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [0])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_1  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [1]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [1])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_10  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [10]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [10])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_11  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [11]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [11])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_12  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [12]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [12])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_13  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [13]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [13])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_14  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [14]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [14])
  );
  (* keep = 32'd1 *)
  (* module_not_derived = 32'd1 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/04_01_2024_09_15_02/bin/../share/yosys/rapidsilicon/genesis3/io_cell_final_map.v:41.13-41.44" *)
  O_BUF \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$dsp_fractured_accum_output_shifted_rounded.P_15  (
    .I(\$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P [15]),
    .O(\$auto$rs_design_edit.cc:682:execute$41199.P [15])
  );
  fabric_dsp_fractured_accum_output_shifted_rounded \$auto$rs_design_edit.cc:680:execute$41198  (
    .\$auto$clkbufmap.cc:298:execute$40576 (\$auto$clkbufmap.cc:298:execute$40576 ),
    .\$iopadmap$A (\$iopadmap$A ),
    .\$iopadmap$B (\$iopadmap$B ),
    .\$iopadmap$P (\$iopadmap$P ),
    .\$iopadmap$load_acc_i (\$iopadmap$load_acc_i ),
    .\$iopadmap$reset (\$iopadmap$reset ),
    .\$iopadmap$round_i (\$iopadmap$round_i ),
    .\$iopadmap$shift_right_i (\$iopadmap$shift_right_i ),
    .\$iopadmap$subtract_i (\$iopadmap$subtract_i )
  );
  assign \$auto$clkbufmap.cc:298:execute$40576  = \$flatten$auto$rs_design_edit.cc:682:execute$41199.$auto$clkbufmap.cc:298:execute$40576 ;
  assign \$iopadmap$A  = \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$A ;
  assign \$iopadmap$B  = \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$B ;
  assign \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$P  = \$iopadmap$P ;
  assign \$iopadmap$load_acc_i  = \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$load_acc_i ;
  assign \$iopadmap$reset  = \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$reset ;
  assign \$iopadmap$round_i  = \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$round_i ;
  assign \$iopadmap$shift_right_i  = \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$shift_right_i ;
  assign \$iopadmap$subtract_i  = \$flatten$auto$rs_design_edit.cc:682:execute$41199.$iopadmap$subtract_i ;
  assign \$auto$rs_design_edit.cc:682:execute$41199.A  = A;
  assign \$auto$rs_design_edit.cc:682:execute$41199.B  = B;
  assign P = \$auto$rs_design_edit.cc:682:execute$41199.P ;
  assign \$auto$rs_design_edit.cc:682:execute$41199.clk  = clk;
  assign \$auto$rs_design_edit.cc:682:execute$41199.load_acc_i  = load_acc_i;
  assign \$auto$rs_design_edit.cc:682:execute$41199.reset  = reset;
  assign \$auto$rs_design_edit.cc:682:execute$41199.round_i  = round_i;
  assign \$auto$rs_design_edit.cc:682:execute$41199.shift_right_i  = shift_right_i;
  assign \$auto$rs_design_edit.cc:682:execute$41199.subtract_i  = subtract_i;
endmodule
