//Verilog generated by VPR  from post-place-and-route implementation
module fabric_primitive_example_design_13 (
    input \$auto$clkbufmap.cc:339:execute$717 ,
    input \$iopadmap$channel_bond_sync_in ,
    input \$iopadmap$i1[0] ,
    input \$iopadmap$i1[1] ,
    input \$iopadmap$i1[2] ,
    input \$iopadmap$i1[3] ,
    input \$iopadmap$i2[0] ,
    input \$iopadmap$i2[1] ,
    input \$iopadmap$i2[2] ,
    input \$iopadmap$i2[3] ,
    input \$iopadmap$load_word ,
    input \$iopadmap$pll_clk ,
    input \$iopadmap$reset ,
    output \data_in[3] ,
    output \$auto$rs_design_edit.cc:492:handle_dangling_outs$754 ,
    output \$auto$rs_design_edit.cc:492:handle_dangling_outs$755 ,
    output \$auto$rs_design_edit.cc:492:handle_dangling_outs$756 ,
    output \$auto$rs_design_edit.cc:615:add_wire_btw_prims$751 ,
    output \$auto$rs_design_edit.cc:615:add_wire_btw_prims$752 ,
    output \$auto$rs_design_edit.cc:615:add_wire_btw_prims$753 ,
    output \data_in[0] ,
    output \data_in[1] ,
    output \data_in[2] ,
    output \output_enable ,
    output \$auto$rs_design_edit.cc:879:execute$738 ,
    output \$auto$rs_design_edit.cc:879:execute$739 ,
    output \$auto$rs_design_edit.cc:879:execute$740 ,
    output \$auto$rs_design_edit.cc:879:execute$741 ,
    output \$auto$rs_design_edit.cc:879:execute$742 ,
    output \$auto$rs_design_edit.cc:879:execute$743 ,
    output \$auto$rs_design_edit.cc:879:execute$744 ,
    output \$auto$rs_design_edit.cc:879:execute$745 ,
    output \$auto$rs_design_edit.cc:879:execute$746 ,
    output \$auto$rs_design_edit.cc:879:execute$747 ,
    output \$auto$rs_design_edit.cc:879:execute$748 ,
    output \$auto$rs_design_edit.cc:879:execute$749 ,
    output \$auto$rs_design_edit.cc:879:execute$750 
);

    //Wires
    wire \$auto$clkbufmap.cc:339:execute$717_output_0_0 ;
    wire \$iopadmap$channel_bond_sync_in_output_0_0 ;
    wire \$iopadmap$i1[0]_output_0_0 ;
    wire \$iopadmap$i1[1]_output_0_0 ;
    wire \$iopadmap$i1[2]_output_0_0 ;
    wire \$iopadmap$i1[3]_output_0_0 ;
    wire \$iopadmap$i2[0]_output_0_0 ;
    wire \$iopadmap$i2[1]_output_0_0 ;
    wire \$iopadmap$i2[2]_output_0_0 ;
    wire \$iopadmap$i2[3]_output_0_0 ;
    wire \$iopadmap$load_word_output_0_0 ;
    wire \$iopadmap$pll_clk_output_0_0 ;
    wire \$iopadmap$reset_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$754_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$755_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$756_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$738_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$739_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$740_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$741_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$742_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$743_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$744_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$745_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$746_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$747_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$748_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$749_output_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$750_output_0_0 ;
    wire \lut_data_in[0]_output_0_0 ;
    wire \lut_data_in[1]_output_0_0 ;
    wire \lut_data_in[2]_output_0_0 ;
    wire \lut_data_in[3]_output_0_0 ;
    wire \dffre_output_enable_output_0_0 ;
    wire \lut_$true_output_0_0 ;
    wire \lut_$abc$709$new_new_n17___output_0_0 ;
    wire \dffre_output_enable_clock_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$754_input_0_3 ;
    wire \lut_data_in[1]_input_0_1 ;
    wire \lut_data_in[2]_input_0_5 ;
    wire \lut_data_in[0]_input_0_3 ;
    wire \lut_$abc$709$new_new_n17___input_0_5 ;
    wire \lut_data_in[1]_input_0_2 ;
    wire \lut_data_in[2]_input_0_4 ;
    wire \lut_$abc$709$new_new_n17___input_0_4 ;
    wire \lut_data_in[2]_input_0_2 ;
    wire \lut_$abc$709$new_new_n17___input_0_2 ;
    wire \lut_data_in[3]_input_0_2 ;
    wire \lut_data_in[1]_input_0_3 ;
    wire \lut_data_in[2]_input_0_1 ;
    wire \lut_data_in[0]_input_0_1 ;
    wire \lut_$abc$709$new_new_n17___input_0_1 ;
    wire \lut_data_in[1]_input_0_4 ;
    wire \lut_data_in[2]_input_0_3 ;
    wire \lut_$abc$709$new_new_n17___input_0_3 ;
    wire \lut_data_in[2]_input_0_0 ;
    wire \lut_$abc$709$new_new_n17___input_0_0 ;
    wire \lut_data_in[3]_input_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_input_0_4 ;
    wire \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$755_input_0_2 ;
    wire \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_input_0_1 ;
    wire \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$756_input_0_3 ;
    wire \dffre_output_enable_input_1_0 ;
    wire \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_input_0_1 ;
    wire \$auto$rs_design_edit.cc:492:handle_dangling_outs$754_input_0_0 ;
    wire \$auto$rs_design_edit.cc:492:handle_dangling_outs$755_input_0_0 ;
    wire \$auto$rs_design_edit.cc:492:handle_dangling_outs$756_input_0_0 ;
    wire \$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_input_0_0 ;
    wire \$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_input_0_0 ;
    wire \$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$738_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$739_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$740_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$741_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$742_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$743_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$744_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$745_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$746_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$747_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$748_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$749_input_0_0 ;
    wire \$auto$rs_design_edit.cc:879:execute$750_input_0_0 ;
    wire \data_in[0]_input_0_0 ;
    wire \data_in[1]_input_0_0 ;
    wire \data_in[2]_input_0_0 ;
    wire \data_in[3]_input_0_0 ;
    wire \output_enable_input_0_0 ;
    wire \dffre_output_enable_input_0_0 ;
    wire \dffre_output_enable_input_2_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$750_input_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$749_input_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$746_input_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$748_input_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$747_input_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$745_input_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$738_input_0_0 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$744_input_0_1 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$742_input_0_2 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$741_input_0_2 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$739_input_0_1 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$740_input_0_1 ;
    wire \lut_$auto$rs_design_edit.cc:879:execute$743_input_0_1 ;
    wire \lut_data_in[3]_input_0_4 ;

    //IO assignments
    assign \data_in[3]  = \data_in[3]_input_0_0 ;
    assign \$auto$rs_design_edit.cc:492:handle_dangling_outs$754  = \$auto$rs_design_edit.cc:492:handle_dangling_outs$754_input_0_0 ;
    assign \$auto$rs_design_edit.cc:492:handle_dangling_outs$755  = \$auto$rs_design_edit.cc:492:handle_dangling_outs$755_input_0_0 ;
    assign \$auto$rs_design_edit.cc:492:handle_dangling_outs$756  = \$auto$rs_design_edit.cc:492:handle_dangling_outs$756_input_0_0 ;
    assign \$auto$rs_design_edit.cc:615:add_wire_btw_prims$751  = \$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_input_0_0 ;
    assign \$auto$rs_design_edit.cc:615:add_wire_btw_prims$752  = \$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_input_0_0 ;
    assign \$auto$rs_design_edit.cc:615:add_wire_btw_prims$753  = \$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_input_0_0 ;
    assign \data_in[0]  = \data_in[0]_input_0_0 ;
    assign \data_in[1]  = \data_in[1]_input_0_0 ;
    assign \data_in[2]  = \data_in[2]_input_0_0 ;
    assign \output_enable  = \output_enable_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$738  = \$auto$rs_design_edit.cc:879:execute$738_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$739  = \$auto$rs_design_edit.cc:879:execute$739_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$740  = \$auto$rs_design_edit.cc:879:execute$740_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$741  = \$auto$rs_design_edit.cc:879:execute$741_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$742  = \$auto$rs_design_edit.cc:879:execute$742_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$743  = \$auto$rs_design_edit.cc:879:execute$743_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$744  = \$auto$rs_design_edit.cc:879:execute$744_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$745  = \$auto$rs_design_edit.cc:879:execute$745_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$746  = \$auto$rs_design_edit.cc:879:execute$746_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$747  = \$auto$rs_design_edit.cc:879:execute$747_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$748  = \$auto$rs_design_edit.cc:879:execute$748_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$749  = \$auto$rs_design_edit.cc:879:execute$749_input_0_0 ;
    assign \$auto$rs_design_edit.cc:879:execute$750  = \$auto$rs_design_edit.cc:879:execute$750_input_0_0 ;
    assign \$auto$clkbufmap.cc:339:execute$717_output_0_0  = \$auto$clkbufmap.cc:339:execute$717 ;
    assign \$iopadmap$channel_bond_sync_in_output_0_0  = \$iopadmap$channel_bond_sync_in ;
    assign \$iopadmap$i1[0]_output_0_0  = \$iopadmap$i1[0] ;
    assign \$iopadmap$i1[1]_output_0_0  = \$iopadmap$i1[1] ;
    assign \$iopadmap$i1[2]_output_0_0  = \$iopadmap$i1[2] ;
    assign \$iopadmap$i1[3]_output_0_0  = \$iopadmap$i1[3] ;
    assign \$iopadmap$i2[0]_output_0_0  = \$iopadmap$i2[0] ;
    assign \$iopadmap$i2[1]_output_0_0  = \$iopadmap$i2[1] ;
    assign \$iopadmap$i2[2]_output_0_0  = \$iopadmap$i2[2] ;
    assign \$iopadmap$i2[3]_output_0_0  = \$iopadmap$i2[3] ;
    assign \$iopadmap$load_word_output_0_0  = \$iopadmap$load_word ;
    assign \$iopadmap$pll_clk_output_0_0  = \$iopadmap$pll_clk ;
    assign \$iopadmap$reset_output_0_0  = \$iopadmap$reset ;

    //Interconnect
    fpga_interconnect \routing_segment_$auto$clkbufmap.cc:339:execute$717_output_0_0_to_dffre_output_enable_clock_0_0  (
        .datain(\$auto$clkbufmap.cc:339:execute$717_output_0_0 ),
        .dataout(\dffre_output_enable_clock_0_0 )
    );

    fpga_interconnect \routing_segment_$iopadmap$channel_bond_sync_in_output_0_0_to_lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$754_input_0_3  (
        .datain(\$iopadmap$channel_bond_sync_in_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$754_input_0_3 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i1[0]_output_0_0_to_lut_data_in[1]_input_0_1  (
        .datain(\$iopadmap$i1[0]_output_0_0 ),
        .dataout(\lut_data_in[1]_input_0_1 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i1[0]_output_0_0_to_lut_data_in[2]_input_0_5  (
        .datain(\$iopadmap$i1[0]_output_0_0 ),
        .dataout(\lut_data_in[2]_input_0_5 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i1[0]_output_0_0_to_lut_data_in[0]_input_0_3  (
        .datain(\$iopadmap$i1[0]_output_0_0 ),
        .dataout(\lut_data_in[0]_input_0_3 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i1[0]_output_0_0_to_lut_$abc$709$new_new_n17___input_0_5  (
        .datain(\$iopadmap$i1[0]_output_0_0 ),
        .dataout(\lut_$abc$709$new_new_n17___input_0_5 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i1[1]_output_0_0_to_lut_data_in[1]_input_0_2  (
        .datain(\$iopadmap$i1[1]_output_0_0 ),
        .dataout(\lut_data_in[1]_input_0_2 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i1[1]_output_0_0_to_lut_data_in[2]_input_0_4  (
        .datain(\$iopadmap$i1[1]_output_0_0 ),
        .dataout(\lut_data_in[2]_input_0_4 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i1[1]_output_0_0_to_lut_$abc$709$new_new_n17___input_0_4  (
        .datain(\$iopadmap$i1[1]_output_0_0 ),
        .dataout(\lut_$abc$709$new_new_n17___input_0_4 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i1[2]_output_0_0_to_lut_data_in[2]_input_0_2  (
        .datain(\$iopadmap$i1[2]_output_0_0 ),
        .dataout(\lut_data_in[2]_input_0_2 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i1[2]_output_0_0_to_lut_$abc$709$new_new_n17___input_0_2  (
        .datain(\$iopadmap$i1[2]_output_0_0 ),
        .dataout(\lut_$abc$709$new_new_n17___input_0_2 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i1[3]_output_0_0_to_lut_data_in[3]_input_0_2  (
        .datain(\$iopadmap$i1[3]_output_0_0 ),
        .dataout(\lut_data_in[3]_input_0_2 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i2[0]_output_0_0_to_lut_data_in[1]_input_0_3  (
        .datain(\$iopadmap$i2[0]_output_0_0 ),
        .dataout(\lut_data_in[1]_input_0_3 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i2[0]_output_0_0_to_lut_data_in[2]_input_0_1  (
        .datain(\$iopadmap$i2[0]_output_0_0 ),
        .dataout(\lut_data_in[2]_input_0_1 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i2[0]_output_0_0_to_lut_data_in[0]_input_0_1  (
        .datain(\$iopadmap$i2[0]_output_0_0 ),
        .dataout(\lut_data_in[0]_input_0_1 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i2[0]_output_0_0_to_lut_$abc$709$new_new_n17___input_0_1  (
        .datain(\$iopadmap$i2[0]_output_0_0 ),
        .dataout(\lut_$abc$709$new_new_n17___input_0_1 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i2[1]_output_0_0_to_lut_data_in[1]_input_0_4  (
        .datain(\$iopadmap$i2[1]_output_0_0 ),
        .dataout(\lut_data_in[1]_input_0_4 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i2[1]_output_0_0_to_lut_data_in[2]_input_0_3  (
        .datain(\$iopadmap$i2[1]_output_0_0 ),
        .dataout(\lut_data_in[2]_input_0_3 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i2[1]_output_0_0_to_lut_$abc$709$new_new_n17___input_0_3  (
        .datain(\$iopadmap$i2[1]_output_0_0 ),
        .dataout(\lut_$abc$709$new_new_n17___input_0_3 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i2[2]_output_0_0_to_lut_data_in[2]_input_0_0  (
        .datain(\$iopadmap$i2[2]_output_0_0 ),
        .dataout(\lut_data_in[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i2[2]_output_0_0_to_lut_$abc$709$new_new_n17___input_0_0  (
        .datain(\$iopadmap$i2[2]_output_0_0 ),
        .dataout(\lut_$abc$709$new_new_n17___input_0_0 )
    );

    fpga_interconnect \routing_segment_$iopadmap$i2[3]_output_0_0_to_lut_data_in[3]_input_0_0  (
        .datain(\$iopadmap$i2[3]_output_0_0 ),
        .dataout(\lut_data_in[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_$iopadmap$load_word_output_0_0_to_lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_input_0_4  (
        .datain(\$iopadmap$load_word_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_input_0_4 )
    );

    fpga_interconnect \routing_segment_$iopadmap$load_word_output_0_0_to_lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$755_input_0_2  (
        .datain(\$iopadmap$load_word_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$755_input_0_2 )
    );

    fpga_interconnect \routing_segment_$iopadmap$pll_clk_output_0_0_to_lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_input_0_1  (
        .datain(\$iopadmap$pll_clk_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_input_0_1 )
    );

    fpga_interconnect \routing_segment_$iopadmap$pll_clk_output_0_0_to_lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$756_input_0_3  (
        .datain(\$iopadmap$pll_clk_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$756_input_0_3 )
    );

    fpga_interconnect \routing_segment_$iopadmap$reset_output_0_0_to_dffre_output_enable_input_1_0  (
        .datain(\$iopadmap$reset_output_0_0 ),
        .dataout(\dffre_output_enable_input_1_0 )
    );

    fpga_interconnect \routing_segment_$iopadmap$reset_output_0_0_to_lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_input_0_1  (
        .datain(\$iopadmap$reset_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$754_output_0_0_to_$auto$rs_design_edit.cc:492:handle_dangling_outs$754_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$754_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:492:handle_dangling_outs$754_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$755_output_0_0_to_$auto$rs_design_edit.cc:492:handle_dangling_outs$755_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$755_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:492:handle_dangling_outs$755_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$756_output_0_0_to_$auto$rs_design_edit.cc:492:handle_dangling_outs$756_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$756_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:492:handle_dangling_outs$756_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_output_0_0_to_$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_output_0_0_to_$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_output_0_0_to_$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$738_output_0_0_to_$auto$rs_design_edit.cc:879:execute$738_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$738_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$738_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$739_output_0_0_to_$auto$rs_design_edit.cc:879:execute$739_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$739_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$739_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$740_output_0_0_to_$auto$rs_design_edit.cc:879:execute$740_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$740_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$740_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$741_output_0_0_to_$auto$rs_design_edit.cc:879:execute$741_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$741_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$741_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$742_output_0_0_to_$auto$rs_design_edit.cc:879:execute$742_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$742_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$742_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$743_output_0_0_to_$auto$rs_design_edit.cc:879:execute$743_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$743_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$743_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$744_output_0_0_to_$auto$rs_design_edit.cc:879:execute$744_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$744_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$744_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$745_output_0_0_to_$auto$rs_design_edit.cc:879:execute$745_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$745_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$745_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$746_output_0_0_to_$auto$rs_design_edit.cc:879:execute$746_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$746_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$746_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$747_output_0_0_to_$auto$rs_design_edit.cc:879:execute$747_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$747_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$747_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$748_output_0_0_to_$auto$rs_design_edit.cc:879:execute$748_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$748_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$748_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$749_output_0_0_to_$auto$rs_design_edit.cc:879:execute$749_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$749_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$749_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$auto$rs_design_edit.cc:879:execute$750_output_0_0_to_$auto$rs_design_edit.cc:879:execute$750_input_0_0  (
        .datain(\lut_$auto$rs_design_edit.cc:879:execute$750_output_0_0 ),
        .dataout(\$auto$rs_design_edit.cc:879:execute$750_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_data_in[0]_output_0_0_to_data_in[0]_input_0_0  (
        .datain(\lut_data_in[0]_output_0_0 ),
        .dataout(\data_in[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_data_in[1]_output_0_0_to_data_in[1]_input_0_0  (
        .datain(\lut_data_in[1]_output_0_0 ),
        .dataout(\data_in[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_data_in[2]_output_0_0_to_data_in[2]_input_0_0  (
        .datain(\lut_data_in[2]_output_0_0 ),
        .dataout(\data_in[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_data_in[3]_output_0_0_to_data_in[3]_input_0_0  (
        .datain(\lut_data_in[3]_output_0_0 ),
        .dataout(\data_in[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_output_enable_output_0_0_to_output_enable_input_0_0  (
        .datain(\dffre_output_enable_output_0_0 ),
        .dataout(\output_enable_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_output_enable_input_0_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_output_enable_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_output_enable_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_output_enable_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$750_input_0_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$750_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$749_input_0_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$749_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$746_input_0_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$746_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$748_input_0_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$748_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$747_input_0_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$747_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$745_input_0_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$745_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$738_input_0_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$738_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$744_input_0_1  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$744_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$742_input_0_2  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$742_input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$741_input_0_2  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$741_input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$739_input_0_1  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$739_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$740_input_0_1  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$740_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_lut_$auto$rs_design_edit.cc:879:execute$743_input_0_1  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\lut_$auto$rs_design_edit.cc:879:execute$743_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_$abc$709$new_new_n17___output_0_0_to_lut_data_in[3]_input_0_4  (
        .datain(\lut_$abc$709$new_new_n17___output_0_0 ),
        .dataout(\lut_data_in[3]_input_0_4 )
    );


    //Cell instances
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01000001000001010001010001010000)
    ) \lut_data_in[1]  (
        .in({
            \lut_data_in[1]_input_0_4 ,
            \lut_data_in[1]_input_0_3 ,
            \lut_data_in[1]_input_0_2 ,
            \lut_data_in[1]_input_0_1 ,
            1'b0
         }),
        .out(\lut_data_in[1]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_output_enable  (
        .C(\dffre_output_enable_clock_0_0 ),
        .D(\dffre_output_enable_input_0_0 ),
        .E(\dffre_output_enable_input_2_0 ),
        .R(\dffre_output_enable_input_1_0 ),
        .Q(\dffre_output_enable_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000001)
    ) \lut_$true  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            1'b0
         }),
        .out(\lut_$true_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000010)
    ) \lut_$auto$rs_design_edit.cc:879:execute$750  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$750_input_0_0 
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$750_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000010)
    ) \lut_$auto$rs_design_edit.cc:879:execute$749  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$749_input_0_0 
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$749_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000010)
    ) \lut_$auto$rs_design_edit.cc:879:execute$746  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$746_input_0_0 
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$746_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000010)
    ) \lut_$auto$rs_design_edit.cc:879:execute$748  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$748_input_0_0 
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$748_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000010)
    ) \lut_$auto$rs_design_edit.cc:879:execute$747  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$747_input_0_0 
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$747_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000010)
    ) \lut_$auto$rs_design_edit.cc:879:execute$745  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$745_input_0_0 
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$745_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000010)
    ) \lut_$auto$rs_design_edit.cc:879:execute$738  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$738_input_0_0 
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$738_output_0_0 )
    );

    LUT_K #(
        .K(6),
        .LUT_MASK(64'b1010010110010110100101100101101010100101010110100101101001011010)
    ) \lut_data_in[2]  (
        .in({
            \lut_data_in[2]_input_0_5 ,
            \lut_data_in[2]_input_0_4 ,
            \lut_data_in[2]_input_0_3 ,
            \lut_data_in[2]_input_0_2 ,
            \lut_data_in[2]_input_0_1 ,
            \lut_data_in[2]_input_0_0 
         }),
        .out(\lut_data_in[2]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000100000100)
    ) \lut_data_in[0]  (
        .in({
            1'b0,
            \lut_data_in[0]_input_0_3 ,
            1'b0,
            \lut_data_in[0]_input_0_1 ,
            1'b0
         }),
        .out(\lut_data_in[0]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000001000010000000000010010)
    ) \lut_data_in[3]  (
        .in({
            \lut_data_in[3]_input_0_4 ,
            1'b0,
            \lut_data_in[3]_input_0_2 ,
            1'b0,
            \lut_data_in[3]_input_0_0 
         }),
        .out(\lut_data_in[3]_output_0_0 )
    );

    LUT_K #(
        .K(6),
        .LUT_MASK(64'b1111101011101000111010001010000011111010101000001010000010100000)
    ) \lut_$abc$709$new_new_n17__  (
        .in({
            \lut_$abc$709$new_new_n17___input_0_5 ,
            \lut_$abc$709$new_new_n17___input_0_4 ,
            \lut_$abc$709$new_new_n17___input_0_3 ,
            \lut_$abc$709$new_new_n17___input_0_2 ,
            \lut_$abc$709$new_new_n17___input_0_1 ,
            \lut_$abc$709$new_new_n17___input_0_0 
         }),
        .out(\lut_$abc$709$new_new_n17___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000100000000)
    ) \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$754  (
        .in({
            1'b0,
            \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$754_input_0_3 ,
            1'b0,
            1'b0,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$754_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000100)
    ) \lut_$auto$rs_design_edit.cc:879:execute$744  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$744_input_0_1 ,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$744_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000100)
    ) \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$752  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_input_0_1 ,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$752_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000010000000000000000)
    ) \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$751  (
        .in({
            \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_input_0_4 ,
            1'b0,
            1'b0,
            1'b0,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$751_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000010000)
    ) \lut_$auto$rs_design_edit.cc:879:execute$742  (
        .in({
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$742_input_0_2 ,
            1'b0,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$742_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000010000)
    ) \lut_$auto$rs_design_edit.cc:879:execute$741  (
        .in({
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$741_input_0_2 ,
            1'b0,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$741_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000100000000)
    ) \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$756  (
        .in({
            1'b0,
            \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$756_input_0_3 ,
            1'b0,
            1'b0,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$756_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000100)
    ) \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$753  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_input_0_1 ,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:615:add_wire_btw_prims$753_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000100)
    ) \lut_$auto$rs_design_edit.cc:879:execute$739  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$739_input_0_1 ,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$739_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000100)
    ) \lut_$auto$rs_design_edit.cc:879:execute$740  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$740_input_0_1 ,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$740_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000010000)
    ) \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$755  (
        .in({
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$755_input_0_2 ,
            1'b0,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:492:handle_dangling_outs$755_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000100)
    ) \lut_$auto$rs_design_edit.cc:879:execute$743  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            \lut_$auto$rs_design_edit.cc:879:execute$743_input_0_1 ,
            1'b0
         }),
        .out(\lut_$auto$rs_design_edit.cc:879:execute$743_output_0_0 )
    );


endmodule
