-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/05_21_2023_09_15_01/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir ../ /nfs_project/gemini/DV/usmanqadir/jira_repo/EDA-1579/./rtl 
-vlog-libdir 
-vlog-define 
-vlog2k /nfs_project/gemini/DV/usmanqadir/jira_repo/EDA-1579/./rtl/b_registered_input_to_output.v
-top b_registered_input_to_output
