create_design rv_core_ibex
target_device 1VG28
add_include_path ./rtl
add_design_file ./rtl/alert_handler_reg_pkg.sv
add_design_file ./rtl/entropy_src_reg_pkg.sv
add_design_file ./rtl/entropy_src_pkg.sv
add_design_file ./rtl/edn_reg_pkg.sv
add_design_file ./rtl/edn_pkg.sv
add_design_file ./rtl/ibex_pkg.sv
add_design_file ./rtl/prim_util_pkg.sv
add_design_file ./rtl/rv_core_ibex_reg_pkg.sv
add_design_file ./rtl/lc_ctrl_pkg.sv
add_design_file ./rtl/prim_alert_pkg.sv
add_design_file ./rtl/prim_cipher_pkg.sv
add_design_file ./rtl/prim_count_pkg.sv
add_design_file ./rtl/prim_esc_pkg.sv
add_design_file ./rtl/prim_mubi_pkg.sv
add_design_file ./rtl/prim_pkg.sv
add_design_file ./rtl/prim_ram_1p_pkg.sv
add_design_file ./rtl/prim_secded_pkg.sv
add_design_file ./rtl/prim_subreg_pkg.sv
add_design_file ./rtl/pwrmgr_reg_pkg.sv
add_design_file ./rtl/pwrmgr_pkg.sv
add_design_file ./rtl/rv_core_ibex_pkg.sv
add_design_file ./rtl/top_pkg.sv
add_design_file ./rtl/tlul_pkg.sv
add_design_file ./rtl/ibex_alu.sv
add_design_file ./rtl/ibex_branch_predict.sv
add_design_file ./rtl/ibex_compressed_decoder.sv
add_design_file ./rtl/ibex_controller.sv
add_design_file ./rtl/ibex_core.sv
add_design_file ./rtl/ibex_counter.sv
add_design_file ./rtl/ibex_cs_registers.sv
add_design_file ./rtl/ibex_csr.sv
add_design_file ./rtl/ibex_decoder.sv
add_design_file ./rtl/ibex_dummy_instr.sv
add_design_file ./rtl/ibex_ex_block.sv
add_design_file ./rtl/ibex_icache.sv
add_design_file ./rtl/ibex_id_stage.sv
add_design_file ./rtl/ibex_if_stage.sv
add_design_file ./rtl/ibex_load_store_unit.sv
add_design_file ./rtl/ibex_lockstep.sv
add_design_file ./rtl/ibex_multdiv_fast.sv
add_design_file ./rtl/ibex_register_file_ff.sv
add_design_file ./rtl/ibex_top.sv
add_design_file ./rtl/ibex_wb_stage.sv
add_design_file ./rtl/prim_alert_sender.sv
add_design_file ./rtl/prim_arbiter_fixed.sv
add_design_file ./rtl/prim_buf.sv
add_design_file ./rtl/prim_clock_gating.sv
add_design_file ./rtl/prim_diff_decode.sv
add_design_file ./rtl/prim_edn_req.sv
add_design_file ./rtl/prim_esc_receiver.sv
add_design_file ./rtl/prim_fifo_sync.sv
add_design_file ./rtl/prim_flop_2sync.sv
add_design_file ./rtl/prim_generic_buf.sv
add_design_file ./rtl/prim_generic_flop.sv
add_design_file ./rtl/prim_generic_flop_2sync.sv
add_design_file ./rtl/prim_generic_ram_1p.sv
add_design_file ./rtl/prim_lc_sync.sv
add_design_file ./rtl/prim_lfsr.sv
add_design_file ./rtl/prim_packer_fifo.sv
add_design_file ./rtl/prim_ram_1p.sv
add_design_file ./rtl/prim_sec_anchor_buf.sv
add_design_file ./rtl/prim_secded_28_22_dec.sv
add_design_file ./rtl/prim_secded_28_22_enc.sv
add_design_file ./rtl/prim_secded_72_64_dec.sv
add_design_file ./rtl/prim_secded_72_64_enc.sv
add_design_file ./rtl/prim_secded_inv_39_32_dec.sv
add_design_file ./rtl/prim_secded_inv_39_32_enc.sv
add_design_file ./rtl/prim_secded_inv_64_57_dec.sv
add_design_file ./rtl/prim_secded_inv_64_57_enc.sv
add_design_file ./rtl/prim_subreg.sv
add_design_file ./rtl/prim_subreg_ext.sv
add_design_file ./rtl/prim_sync_reqack.sv
add_design_file ./rtl/rv_core_addr_trans.sv
add_design_file ./rtl/rv_core_ibex.sv
add_design_file ./rtl/rv_core_ibex_cfg_reg_top.sv
add_design_file ./rtl/tlul_adapter_host.sv
add_design_file ./rtl/tlul_adapter_reg.sv
add_design_file ./rtl/tlul_cmd_intg_chk.sv
add_design_file ./rtl/tlul_cmd_intg_gen.sv
add_design_file ./rtl/tlul_data_integ_dec.sv
add_design_file ./rtl/tlul_data_integ_enc.sv
add_design_file ./rtl/tlul_err.sv
add_design_file ./rtl/tlul_fifo_sync.sv
add_design_file ./rtl/tlul_rsp_intg_chk.sv
add_design_file ./rtl/tlul_rsp_intg_gen.sv
add_design_file ./rtl/wav_cgc_rl.sv
set_top_module rv_core_ibex
add_constraint_file ./raptor_sdc.sdc
analyze
synthesize delay
packing
place
route
sta
power
bitstream 
