-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/04_28_2023_10_25_04/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir /nfs_scratch/scratch/CompilerValidation/abdul_hameed/BASHING/ram_dsp_mix_random/rtl 
-vlog-libdir 
-vlog-define 
-vlog2k /nfs_scratch/scratch/CompilerValidation/abdul_hameed/BASHING/ram_dsp_mix_random/rtl/ram_dsp_mix_random.v
