-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/07_11_2023_09_15_01/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir ../../../../ /nfs_project/gemini/DV/usmanqadir/ring_counter_1ge100_es1 
-vlog-libdir 
-vlog-define 
-vlog2k /nfs_project/gemini/DV/usmanqadir/ring_counter_1ge100_es1/ring_counter.v
-top ring_counter
