create_design ram_simple_dp_synch_undefined_collision_512x16_block
target_device GEMINI_COMPACT_104x68
add_include_path ./rtl
add_library_path ./rtl
add_library_ext .v .sv
add_design_file ./rtl/ram_simple_dp_synch_undefined_collision_512x16_block.v
set_top_module ram_simple_dp_synch_undefined_collision_512x16_block
analyze
synthesize delay
