-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/06_20_2023_09_15_01/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir .././rtl ../ /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl 
-vlog-libdir .././rtl 
-vlog-libext .v
-vlog-libext .sv
-vlog-define 
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/y_shifter.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/fast_main_top.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/contig_processor.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/NMS.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/main_part.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/NMS_top.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/corner_score.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/yx_shifter.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/FAST_with_NMS.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/input_fifo.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/NMS_FIFO.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/x_shifter.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/VHDL_designs/FPGA-FAST/jira/./rtl/FAST_with_NMS.vhd
-top FAST_with_NMS
