//Verilog generated by VPR  from post-place-and-route implementation
module ram_true_dp_dc_16384x9_post_route (
    input \clkA ,
    input \clkB ,
    input \weA ,
    input \weB ,
    input \addrA[12] ,
    input \addrA[13] ,
    input \addrB[12] ,
    input \addrB[13] ,
    output \doutA[0] ,
    output \doutA[1] ,
    output \doutA[2] ,
    output \doutA[3] ,
    output \doutA[4] ,
    output \doutA[5] ,
    output \doutA[6] ,
    output \doutA[7] ,
    output \doutA[8] ,
    output \doutB[0] ,
    output \doutB[1] ,
    output \doutB[2] ,
    output \doutB[3] ,
    output \doutB[4] ,
    output \doutB[5] ,
    output \doutB[6] ,
    output \doutB[7] ,
    output \doutB[8] 
);

    //Wires
    wire \clkA_output_0_0 ;
    wire \clkB_output_0_0 ;
    wire \weA_output_0_0 ;
    wire \weB_output_0_0 ;
    wire \addrA[12]_output_0_0 ;
    wire \addrA[13]_output_0_0 ;
    wire \addrB[12]_output_0_0 ;
    wire \addrB[13]_output_0_0 ;
    wire \lut_doutA[0]_output_0_0 ;
    wire \lut_doutA[1]_output_0_0 ;
    wire \lut_doutA[2]_output_0_0 ;
    wire \lut_doutA[3]_output_0_0 ;
    wire \lut_doutA[4]_output_0_0 ;
    wire \lut_doutA[5]_output_0_0 ;
    wire \lut_doutA[6]_output_0_0 ;
    wire \lut_doutA[7]_output_0_0 ;
    wire \lut_doutA[8]_output_0_0 ;
    wire \lut_doutB[0]_output_0_0 ;
    wire \lut_doutB[1]_output_0_0 ;
    wire \lut_doutB[2]_output_0_0 ;
    wire \lut_doutB[3]_output_0_0 ;
    wire \lut_doutB[4]_output_0_0 ;
    wire \lut_doutB[5]_output_0_0 ;
    wire \lut_doutB[6]_output_0_0 ;
    wire \lut_doutB[7]_output_0_0 ;
    wire \lut_doutB[8]_output_0_0 ;
    wire \lut_$true_output_0_0 ;
    wire \lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0 ;
    wire \lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[0]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[1]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[2]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[3]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[4]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[5]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[6]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[7]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[8]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[0]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[1]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[2]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[3]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[4]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[5]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[6]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[7]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[8]_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0 ;
    wire \lut_$abc$4367$new_new_n133___output_0_0 ;
    wire \lut_$abc$4367$new_new_n135___output_0_0 ;
    wire \lut_$abc$4367$new_new_n138___output_0_0 ;
    wire \lut_$abc$4367$new_new_n141___output_0_0 ;
    wire \lut_$abc$4367$new_new_n143___output_0_0 ;
    wire \lut_$abc$4367$new_new_n145___output_0_0 ;
    wire \lut_$abc$4367$new_new_n147___output_0_0 ;
    wire \lut_$abc$4367$new_new_n150___output_0_0 ;
    wire \lut_$abc$4367$new_new_n153___output_0_0 ;
    wire \lut_$abc$4367$new_new_n155___output_0_0 ;
    wire \lut_$abc$4367$new_new_n159___output_0_0 ;
    wire \lut_$abc$4367$new_new_n161___output_0_0 ;
    wire \lut_$abc$4367$new_new_n163___output_0_0 ;
    wire \lut_$abc$4367$new_new_n165___output_0_0 ;
    wire \lut_$abc$4367$new_new_n167___output_0_0 ;
    wire \lut_$abc$4367$new_new_n170___output_0_0 ;
    wire \lut_$abc$4367$new_new_n172___output_0_0 ;
    wire \lut_$abc$4367$new_new_n174___output_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[7]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[2]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[4]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[8]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2267:execute$89_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[0]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[5]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[3]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[1]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[6]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[6]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[2]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[1]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[4]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[8]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2267:execute$82_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[0]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[7]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[3]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[5]_clock_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_2_0 ;
    wire \lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_2_0 ;
    wire \lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_0_0 ;
    wire \doutA[0]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_0_0 ;
    wire \doutA[1]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_0_0 ;
    wire \doutA[2]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_0_0 ;
    wire \doutA[3]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_0_0 ;
    wire \doutA[4]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_0_0 ;
    wire \doutA[5]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_0_0 ;
    wire \doutA[6]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_0_0 ;
    wire \doutA[7]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_0_0 ;
    wire \doutA[8]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_0_0 ;
    wire \doutB[0]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_0_0 ;
    wire \doutB[1]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_0_0 ;
    wire \doutB[2]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_0_0 ;
    wire \doutB[3]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_0_0 ;
    wire \doutB[4]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_0_0 ;
    wire \doutB[5]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_0_0 ;
    wire \doutB[6]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_0_0 ;
    wire \doutB[7]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_0_0 ;
    wire \doutB[8]_input_0_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2267:execute$82_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2267:execute$82_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2267:execute$89_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2267:execute$89_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_1_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2267:execute$89_input_0_0 ;
    wire \lut_$abc$4367$new_new_n174___input_0_3 ;
    wire \lut_$abc$4367$new_new_n161___input_0_0 ;
    wire \lut_$abc$4367$new_new_n172___input_0_3 ;
    wire \lut_$abc$4367$new_new_n143___input_0_0 ;
    wire \lut_$abc$4367$new_new_n170___input_0_0 ;
    wire \lut_$abc$4367$new_new_n167___input_0_3 ;
    wire \lut_$abc$4367$new_new_n159___input_0_0 ;
    wire \lut_$abc$4367$new_new_n163___input_0_4 ;
    wire \lut_$abc$4367$new_new_n133___input_0_3 ;
    wire \lut_$abc$4367$new_new_n174___input_0_1 ;
    wire \lut_$abc$4367$new_new_n161___input_0_1 ;
    wire \lut_$abc$4367$new_new_n172___input_0_1 ;
    wire \lut_$abc$4367$new_new_n143___input_0_3 ;
    wire \lut_$abc$4367$new_new_n170___input_0_1 ;
    wire \lut_$abc$4367$new_new_n167___input_0_0 ;
    wire \lut_$abc$4367$new_new_n159___input_0_4 ;
    wire \lut_$abc$4367$new_new_n163___input_0_2 ;
    wire \lut_$abc$4367$new_new_n133___input_0_2 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_2_0 ;
    wire \dffre_$auto$memory_libmap.cc:2267:execute$82_input_0_0 ;
    wire \lut_$abc$4367$new_new_n141___input_0_0 ;
    wire \lut_$abc$4367$new_new_n145___input_0_0 ;
    wire \lut_$abc$4367$new_new_n147___input_0_4 ;
    wire \lut_$abc$4367$new_new_n155___input_0_2 ;
    wire \lut_$abc$4367$new_new_n138___input_0_2 ;
    wire \lut_$abc$4367$new_new_n135___input_0_3 ;
    wire \lut_$abc$4367$new_new_n165___input_0_4 ;
    wire \lut_$abc$4367$new_new_n150___input_0_3 ;
    wire \lut_$abc$4367$new_new_n153___input_0_3 ;
    wire \lut_$abc$4367$new_new_n141___input_0_3 ;
    wire \lut_$abc$4367$new_new_n145___input_0_3 ;
    wire \lut_$abc$4367$new_new_n147___input_0_3 ;
    wire \lut_$abc$4367$new_new_n155___input_0_0 ;
    wire \lut_$abc$4367$new_new_n138___input_0_3 ;
    wire \lut_$abc$4367$new_new_n135___input_0_2 ;
    wire \lut_$abc$4367$new_new_n165___input_0_2 ;
    wire \lut_$abc$4367$new_new_n150___input_0_0 ;
    wire \lut_$abc$4367$new_new_n153___input_0_4 ;
    wire \lut_doutB[0]_input_0_3 ;
    wire \lut_doutB[1]_input_0_4 ;
    wire \lut_doutB[2]_input_0_2 ;
    wire \lut_doutB[3]_input_0_4 ;
    wire \lut_doutB[4]_input_0_1 ;
    wire \lut_doutB[5]_input_0_0 ;
    wire \lut_doutB[6]_input_0_1 ;
    wire \lut_doutB[7]_input_0_4 ;
    wire \lut_doutB[8]_input_0_1 ;
    wire \lut_doutA[0]_input_0_1 ;
    wire \lut_doutA[1]_input_0_4 ;
    wire \lut_doutA[2]_input_0_1 ;
    wire \lut_doutA[3]_input_0_3 ;
    wire \lut_doutA[4]_input_0_4 ;
    wire \lut_doutA[5]_input_0_3 ;
    wire \lut_doutA[6]_input_0_3 ;
    wire \lut_doutA[7]_input_0_0 ;
    wire \lut_doutA[8]_input_0_4 ;
    wire \lut_doutB[2]_input_0_4 ;
    wire \lut_doutB[1]_input_0_1 ;
    wire \lut_doutB[3]_input_0_1 ;
    wire \lut_doutB[6]_input_0_4 ;
    wire \lut_doutB[4]_input_0_3 ;
    wire \lut_doutB[5]_input_0_1 ;
    wire \lut_doutB[0]_input_0_4 ;
    wire \lut_doutB[8]_input_0_4 ;
    wire \lut_doutB[7]_input_0_1 ;
    wire \lut_doutA[7]_input_0_4 ;
    wire \lut_doutA[2]_input_0_2 ;
    wire \lut_doutA[4]_input_0_0 ;
    wire \lut_doutA[6]_input_0_2 ;
    wire \lut_doutA[8]_input_0_3 ;
    wire \lut_doutA[0]_input_0_2 ;
    wire \lut_doutA[5]_input_0_1 ;
    wire \lut_doutA[3]_input_0_1 ;
    wire \lut_doutA[1]_input_0_1 ;
    wire \lut_doutA[5]_input_0_0 ;
    wire \lut_doutB[0]_input_0_0 ;
    wire \lut_doutB[4]_input_0_4 ;
    wire \lut_doutB[6]_input_0_0 ;
    wire \lut_doutA[4]_input_0_3 ;
    wire \lut_doutB[2]_input_0_1 ;
    wire \lut_doutB[1]_input_0_2 ;
    wire \lut_doutB[7]_input_0_0 ;
    wire \lut_doutB[5]_input_0_3 ;
    wire \lut_doutB[3]_input_0_3 ;
    wire \lut_doutA[1]_input_0_0 ;
    wire \lut_doutA[2]_input_0_4 ;
    wire \lut_doutA[0]_input_0_4 ;
    wire \lut_doutB[8]_input_0_2 ;
    wire \lut_doutA[3]_input_0_0 ;
    wire \lut_doutA[6]_input_0_4 ;
    wire \lut_doutA[7]_input_0_2 ;
    wire \lut_doutA[8]_input_0_0 ;

    //IO assignments
    assign \doutA[0]  = \doutA[0]_input_0_0 ;
    assign \doutA[1]  = \doutA[1]_input_0_0 ;
    assign \doutA[2]  = \doutA[2]_input_0_0 ;
    assign \doutA[3]  = \doutA[3]_input_0_0 ;
    assign \doutA[4]  = \doutA[4]_input_0_0 ;
    assign \doutA[5]  = \doutA[5]_input_0_0 ;
    assign \doutA[6]  = \doutA[6]_input_0_0 ;
    assign \doutA[7]  = \doutA[7]_input_0_0 ;
    assign \doutA[8]  = \doutA[8]_input_0_0 ;
    assign \doutB[0]  = \doutB[0]_input_0_0 ;
    assign \doutB[1]  = \doutB[1]_input_0_0 ;
    assign \doutB[2]  = \doutB[2]_input_0_0 ;
    assign \doutB[3]  = \doutB[3]_input_0_0 ;
    assign \doutB[4]  = \doutB[4]_input_0_0 ;
    assign \doutB[5]  = \doutB[5]_input_0_0 ;
    assign \doutB[6]  = \doutB[6]_input_0_0 ;
    assign \doutB[7]  = \doutB[7]_input_0_0 ;
    assign \doutB[8]  = \doutB[8]_input_0_0 ;
    assign \clkA_output_0_0  = \clkA ;
    assign \clkB_output_0_0  = \clkB ;
    assign \weA_output_0_0  = \weA ;
    assign \weB_output_0_0  = \weB ;
    assign \addrA[12]_output_0_0  = \addrA[12] ;
    assign \addrA[13]_output_0_0  = \addrA[13] ;
    assign \addrB[12]_output_0_0  = \addrB[12] ;
    assign \addrB[13]_output_0_0  = \addrB[13] ;

    //Interconnect
    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[7]_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[7]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[2]_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[2]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[4]_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[4]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[8]_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[8]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:2267:execute$89_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2267:execute$89_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[0]_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[0]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[5]_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[5]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[3]_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[3]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[1]_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[1]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[6]_clock_0_0  (
        .datain(\clkA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[6]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[6]_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[6]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[2]_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[2]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[1]_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[1]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[4]_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[4]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[8]_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[8]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:2267:execute$82_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2267:execute$82_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[0]_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[0]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[7]_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[7]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[3]_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[3]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clkB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[5]_clock_0_0  (
        .datain(\clkB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[5]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_weA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_2_0  (
        .datain(\weA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_2_0  (
        .datain(\weA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_2_0  (
        .datain(\weA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_2_0  (
        .datain(\weA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_2_0  (
        .datain(\weA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_2_0  (
        .datain(\weA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_2_0  (
        .datain(\weA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_2_0  (
        .datain(\weA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weA_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_2_0  (
        .datain(\weA_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weA_output_0_0_to_lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_input_0_0  (
        .datain(\weA_output_0_0 ),
        .dataout(\lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_input_0_0 )
    );

    fpga_interconnect \routing_segment_weB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_2_0  (
        .datain(\weB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_2_0  (
        .datain(\weB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_2_0  (
        .datain(\weB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_2_0  (
        .datain(\weB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weB_output_0_0_to_lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_input_0_0  (
        .datain(\weB_output_0_0 ),
        .dataout(\lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_input_0_0 )
    );

    fpga_interconnect \routing_segment_weB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_2_0  (
        .datain(\weB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_2_0  (
        .datain(\weB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_2_0  (
        .datain(\weB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_2_0  (
        .datain(\weB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_2_0 )
    );

    fpga_interconnect \routing_segment_weB_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_2_0  (
        .datain(\weB_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_2_0 )
    );

    fpga_interconnect \routing_segment_addrA[12]_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_0_0  (
        .datain(\addrA[12]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_addrA[13]_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_0_0  (
        .datain(\addrA[13]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_addrB[12]_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_0_0  (
        .datain(\addrB[12]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_addrB[13]_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_0_0  (
        .datain(\addrB[13]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[0]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_0_0  (
        .datain(\lut_doutA[0]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[0]_output_0_0_to_doutA[0]_input_0_0  (
        .datain(\lut_doutA[0]_output_0_0 ),
        .dataout(\doutA[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[1]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_0_0  (
        .datain(\lut_doutA[1]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[1]_output_0_0_to_doutA[1]_input_0_0  (
        .datain(\lut_doutA[1]_output_0_0 ),
        .dataout(\doutA[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[2]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_0_0  (
        .datain(\lut_doutA[2]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[2]_output_0_0_to_doutA[2]_input_0_0  (
        .datain(\lut_doutA[2]_output_0_0 ),
        .dataout(\doutA[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[3]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_0_0  (
        .datain(\lut_doutA[3]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[3]_output_0_0_to_doutA[3]_input_0_0  (
        .datain(\lut_doutA[3]_output_0_0 ),
        .dataout(\doutA[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[4]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_0_0  (
        .datain(\lut_doutA[4]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[4]_output_0_0_to_doutA[4]_input_0_0  (
        .datain(\lut_doutA[4]_output_0_0 ),
        .dataout(\doutA[4]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[5]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_0_0  (
        .datain(\lut_doutA[5]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[5]_output_0_0_to_doutA[5]_input_0_0  (
        .datain(\lut_doutA[5]_output_0_0 ),
        .dataout(\doutA[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[6]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_0_0  (
        .datain(\lut_doutA[6]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[6]_output_0_0_to_doutA[6]_input_0_0  (
        .datain(\lut_doutA[6]_output_0_0 ),
        .dataout(\doutA[6]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[7]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_0_0  (
        .datain(\lut_doutA[7]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[7]_output_0_0_to_doutA[7]_input_0_0  (
        .datain(\lut_doutA[7]_output_0_0 ),
        .dataout(\doutA[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[8]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_0_0  (
        .datain(\lut_doutA[8]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutA[8]_output_0_0_to_doutA[8]_input_0_0  (
        .datain(\lut_doutA[8]_output_0_0 ),
        .dataout(\doutA[8]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[0]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_0_0  (
        .datain(\lut_doutB[0]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[0]_output_0_0_to_doutB[0]_input_0_0  (
        .datain(\lut_doutB[0]_output_0_0 ),
        .dataout(\doutB[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[1]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_0_0  (
        .datain(\lut_doutB[1]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[1]_output_0_0_to_doutB[1]_input_0_0  (
        .datain(\lut_doutB[1]_output_0_0 ),
        .dataout(\doutB[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[2]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_0_0  (
        .datain(\lut_doutB[2]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[2]_output_0_0_to_doutB[2]_input_0_0  (
        .datain(\lut_doutB[2]_output_0_0 ),
        .dataout(\doutB[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[3]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_0_0  (
        .datain(\lut_doutB[3]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[3]_output_0_0_to_doutB[3]_input_0_0  (
        .datain(\lut_doutB[3]_output_0_0 ),
        .dataout(\doutB[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[4]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_0_0  (
        .datain(\lut_doutB[4]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[4]_output_0_0_to_doutB[4]_input_0_0  (
        .datain(\lut_doutB[4]_output_0_0 ),
        .dataout(\doutB[4]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[5]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_0_0  (
        .datain(\lut_doutB[5]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[5]_output_0_0_to_doutB[5]_input_0_0  (
        .datain(\lut_doutB[5]_output_0_0 ),
        .dataout(\doutB[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[6]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_0_0  (
        .datain(\lut_doutB[6]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[6]_output_0_0_to_doutB[6]_input_0_0  (
        .datain(\lut_doutB[6]_output_0_0 ),
        .dataout(\doutB[6]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[7]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_0_0  (
        .datain(\lut_doutB[7]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[7]_output_0_0_to_doutB[7]_input_0_0  (
        .datain(\lut_doutB[7]_output_0_0 ),
        .dataout(\doutB[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[8]_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_0_0  (
        .datain(\lut_doutB[8]_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_doutB[8]_output_0_0_to_doutB[8]_input_0_0  (
        .datain(\lut_doutB[8]_output_0_0 ),
        .dataout(\doutB[8]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2267:execute$82_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2267:execute$82_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2267:execute$82_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2267:execute$82_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2267:execute$89_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2267:execute$89_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2267:execute$89_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2267:execute$89_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_2_0  (
        .datain(\lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_2_0  (
        .datain(\lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_output_0_0_to_dffre_$auto$memory_libmap.cc:2267:execute$89_input_0_0  (
        .datain(\lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2267:execute$89_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0_to_lut_$abc$4367$new_new_n174___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n174___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0_to_lut_$abc$4367$new_new_n161___input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n161___input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0_to_lut_$abc$4367$new_new_n172___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n172___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0_to_lut_$abc$4367$new_new_n143___input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n143___input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0_to_lut_$abc$4367$new_new_n170___input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n170___input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0_to_lut_$abc$4367$new_new_n167___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n167___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0_to_lut_$abc$4367$new_new_n159___input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n159___input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0_to_lut_$abc$4367$new_new_n163___input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n163___input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0_to_lut_$abc$4367$new_new_n133___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n133___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0_to_lut_$abc$4367$new_new_n174___input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n174___input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0_to_lut_$abc$4367$new_new_n161___input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n161___input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0_to_lut_$abc$4367$new_new_n172___input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n172___input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0_to_lut_$abc$4367$new_new_n143___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n143___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0_to_lut_$abc$4367$new_new_n170___input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n170___input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0_to_lut_$abc$4367$new_new_n167___input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n167___input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0_to_lut_$abc$4367$new_new_n159___input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n159___input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0_to_lut_$abc$4367$new_new_n163___input_0_2  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n163___input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0_to_lut_$abc$4367$new_new_n133___input_0_2  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n133___input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_2_0  (
        .datain(\lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_output_0_0_to_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_2_0  (
        .datain(\lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_output_0_0_to_dffre_$auto$memory_libmap.cc:2267:execute$82_input_0_0  (
        .datain(\lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_output_0_0 ),
        .dataout(\dffre_$auto$memory_libmap.cc:2267:execute$82_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0_to_lut_$abc$4367$new_new_n141___input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n141___input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0_to_lut_$abc$4367$new_new_n145___input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n145___input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0_to_lut_$abc$4367$new_new_n147___input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n147___input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0_to_lut_$abc$4367$new_new_n155___input_0_2  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n155___input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0_to_lut_$abc$4367$new_new_n138___input_0_2  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n138___input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0_to_lut_$abc$4367$new_new_n135___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n135___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0_to_lut_$abc$4367$new_new_n165___input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n165___input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0_to_lut_$abc$4367$new_new_n150___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n150___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0_to_lut_$abc$4367$new_new_n153___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n153___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0_to_lut_$abc$4367$new_new_n141___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n141___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0_to_lut_$abc$4367$new_new_n145___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n145___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0_to_lut_$abc$4367$new_new_n147___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n147___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0_to_lut_$abc$4367$new_new_n155___input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n155___input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0_to_lut_$abc$4367$new_new_n138___input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n138___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0_to_lut_$abc$4367$new_new_n135___input_0_2  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n135___input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0_to_lut_$abc$4367$new_new_n165___input_0_2  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n165___input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0_to_lut_$abc$4367$new_new_n150___input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n150___input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0_to_lut_$abc$4367$new_new_n153___input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0 ),
        .dataout(\lut_$abc$4367$new_new_n153___input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$81[0]_output_0_0_to_lut_doutB[0]_input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$81[0]_output_0_0 ),
        .dataout(\lut_doutB[0]_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$81[1]_output_0_0_to_lut_doutB[1]_input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$81[1]_output_0_0 ),
        .dataout(\lut_doutB[1]_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$81[2]_output_0_0_to_lut_doutB[2]_input_0_2  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$81[2]_output_0_0 ),
        .dataout(\lut_doutB[2]_input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$81[3]_output_0_0_to_lut_doutB[3]_input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$81[3]_output_0_0 ),
        .dataout(\lut_doutB[3]_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$81[4]_output_0_0_to_lut_doutB[4]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$81[4]_output_0_0 ),
        .dataout(\lut_doutB[4]_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$81[5]_output_0_0_to_lut_doutB[5]_input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$81[5]_output_0_0 ),
        .dataout(\lut_doutB[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$81[6]_output_0_0_to_lut_doutB[6]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$81[6]_output_0_0 ),
        .dataout(\lut_doutB[6]_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$81[7]_output_0_0_to_lut_doutB[7]_input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$81[7]_output_0_0 ),
        .dataout(\lut_doutB[7]_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$81[8]_output_0_0_to_lut_doutB[8]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$81[8]_output_0_0 ),
        .dataout(\lut_doutB[8]_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$88[0]_output_0_0_to_lut_doutA[0]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$88[0]_output_0_0 ),
        .dataout(\lut_doutA[0]_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$88[1]_output_0_0_to_lut_doutA[1]_input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$88[1]_output_0_0 ),
        .dataout(\lut_doutA[1]_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$88[2]_output_0_0_to_lut_doutA[2]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$88[2]_output_0_0 ),
        .dataout(\lut_doutA[2]_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$88[3]_output_0_0_to_lut_doutA[3]_input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$88[3]_output_0_0 ),
        .dataout(\lut_doutA[3]_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$88[4]_output_0_0_to_lut_doutA[4]_input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$88[4]_output_0_0 ),
        .dataout(\lut_doutA[4]_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$88[5]_output_0_0_to_lut_doutA[5]_input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$88[5]_output_0_0 ),
        .dataout(\lut_doutA[5]_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$88[6]_output_0_0_to_lut_doutA[6]_input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$88[6]_output_0_0 ),
        .dataout(\lut_doutA[6]_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$88[7]_output_0_0_to_lut_doutA[7]_input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$88[7]_output_0_0 ),
        .dataout(\lut_doutA[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2266:execute$88[8]_output_0_0_to_lut_doutA[8]_input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:2266:execute$88[8]_output_0_0 ),
        .dataout(\lut_doutA[8]_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0_to_lut_doutB[2]_input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0 ),
        .dataout(\lut_doutB[2]_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0_to_lut_doutB[1]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0 ),
        .dataout(\lut_doutB[1]_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0_to_lut_doutB[3]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0 ),
        .dataout(\lut_doutB[3]_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0_to_lut_doutB[6]_input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0 ),
        .dataout(\lut_doutB[6]_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0_to_lut_doutB[4]_input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0 ),
        .dataout(\lut_doutB[4]_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0_to_lut_doutB[5]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0 ),
        .dataout(\lut_doutB[5]_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0_to_lut_doutB[0]_input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0 ),
        .dataout(\lut_doutB[0]_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0_to_lut_doutB[8]_input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0 ),
        .dataout(\lut_doutB[8]_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0_to_lut_doutB[7]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0 ),
        .dataout(\lut_doutB[7]_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0_to_lut_doutA[7]_input_0_4  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0 ),
        .dataout(\lut_doutA[7]_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0_to_lut_doutA[2]_input_0_2  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0 ),
        .dataout(\lut_doutA[2]_input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0_to_lut_doutA[4]_input_0_0  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0 ),
        .dataout(\lut_doutA[4]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0_to_lut_doutA[6]_input_0_2  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0 ),
        .dataout(\lut_doutA[6]_input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0_to_lut_doutA[8]_input_0_3  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0 ),
        .dataout(\lut_doutA[8]_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0_to_lut_doutA[0]_input_0_2  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0 ),
        .dataout(\lut_doutA[0]_input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0_to_lut_doutA[5]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0 ),
        .dataout(\lut_doutA[5]_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0_to_lut_doutA[3]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0 ),
        .dataout(\lut_doutA[3]_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0_to_lut_doutA[1]_input_0_1  (
        .datain(\dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0 ),
        .dataout(\lut_doutA[1]_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n133___output_0_0_to_lut_doutA[5]_input_0_0  (
        .datain(\lut_$abc$4367$new_new_n133___output_0_0 ),
        .dataout(\lut_doutA[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n135___output_0_0_to_lut_doutB[0]_input_0_0  (
        .datain(\lut_$abc$4367$new_new_n135___output_0_0 ),
        .dataout(\lut_doutB[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n138___output_0_0_to_lut_doutB[4]_input_0_4  (
        .datain(\lut_$abc$4367$new_new_n138___output_0_0 ),
        .dataout(\lut_doutB[4]_input_0_4 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n141___output_0_0_to_lut_doutB[6]_input_0_0  (
        .datain(\lut_$abc$4367$new_new_n141___output_0_0 ),
        .dataout(\lut_doutB[6]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n143___output_0_0_to_lut_doutA[4]_input_0_3  (
        .datain(\lut_$abc$4367$new_new_n143___output_0_0 ),
        .dataout(\lut_doutA[4]_input_0_3 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n145___output_0_0_to_lut_doutB[2]_input_0_1  (
        .datain(\lut_$abc$4367$new_new_n145___output_0_0 ),
        .dataout(\lut_doutB[2]_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n147___output_0_0_to_lut_doutB[1]_input_0_2  (
        .datain(\lut_$abc$4367$new_new_n147___output_0_0 ),
        .dataout(\lut_doutB[1]_input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n150___output_0_0_to_lut_doutB[7]_input_0_0  (
        .datain(\lut_$abc$4367$new_new_n150___output_0_0 ),
        .dataout(\lut_doutB[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n153___output_0_0_to_lut_doutB[5]_input_0_3  (
        .datain(\lut_$abc$4367$new_new_n153___output_0_0 ),
        .dataout(\lut_doutB[5]_input_0_3 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n155___output_0_0_to_lut_doutB[3]_input_0_3  (
        .datain(\lut_$abc$4367$new_new_n155___output_0_0 ),
        .dataout(\lut_doutB[3]_input_0_3 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n159___output_0_0_to_lut_doutA[1]_input_0_0  (
        .datain(\lut_$abc$4367$new_new_n159___output_0_0 ),
        .dataout(\lut_doutA[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n161___output_0_0_to_lut_doutA[2]_input_0_4  (
        .datain(\lut_$abc$4367$new_new_n161___output_0_0 ),
        .dataout(\lut_doutA[2]_input_0_4 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n163___output_0_0_to_lut_doutA[0]_input_0_4  (
        .datain(\lut_$abc$4367$new_new_n163___output_0_0 ),
        .dataout(\lut_doutA[0]_input_0_4 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n165___output_0_0_to_lut_doutB[8]_input_0_2  (
        .datain(\lut_$abc$4367$new_new_n165___output_0_0 ),
        .dataout(\lut_doutB[8]_input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n167___output_0_0_to_lut_doutA[3]_input_0_0  (
        .datain(\lut_$abc$4367$new_new_n167___output_0_0 ),
        .dataout(\lut_doutA[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n170___output_0_0_to_lut_doutA[6]_input_0_4  (
        .datain(\lut_$abc$4367$new_new_n170___output_0_0 ),
        .dataout(\lut_doutA[6]_input_0_4 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n172___output_0_0_to_lut_doutA[7]_input_0_2  (
        .datain(\lut_$abc$4367$new_new_n172___output_0_0 ),
        .dataout(\lut_doutA[7]_input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_$abc$4367$new_new_n174___output_0_0_to_lut_doutA[8]_input_0_0  (
        .datain(\lut_$abc$4367$new_new_n174___output_0_0 ),
        .dataout(\lut_doutA[8]_input_0_0 )
    );


    //Cell instances
    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]  (
        .C(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[1]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00110011010111111111111101011111)
    ) \lut_$abc$4367$new_new_n141__  (
        .in({
            1'b0,
            \lut_$abc$4367$new_new_n141___input_0_3 ,
            1'b0,
            1'b0,
            \lut_$abc$4367$new_new_n141___input_0_0 
         }),
        .out(\lut_$abc$4367$new_new_n141___output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]  (
        .C(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:1544:generate_mux$93[0]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$81[6]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$81[6]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$81[6]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$81[6]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b10101010000110111111111100011011)
    ) \lut_$abc$4367$new_new_n145__  (
        .in({
            1'b0,
            \lut_$abc$4367$new_new_n145___input_0_3 ,
            1'b0,
            1'b0,
            \lut_$abc$4367$new_new_n145___input_0_0 
         }),
        .out(\lut_$abc$4367$new_new_n145___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000100010000000001010000)
    ) \lut_doutB[2]  (
        .in({
            \lut_doutB[2]_input_0_4 ,
            1'b0,
            \lut_doutB[2]_input_0_2 ,
            \lut_doutB[2]_input_0_1 ,
            1'b0
         }),
        .out(\lut_doutB[2]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01010101111111110000111100110011)
    ) \lut_$abc$4367$new_new_n147__  (
        .in({
            \lut_$abc$4367$new_new_n147___input_0_4 ,
            \lut_$abc$4367$new_new_n147___input_0_3 ,
            1'b0,
            1'b0,
            1'b0
         }),
        .out(\lut_$abc$4367$new_new_n147___output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$81[2]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$81[2]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$81[2]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$81[2]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000101010000000000000100)
    ) \lut_doutB[1]  (
        .in({
            \lut_doutB[1]_input_0_4 ,
            1'b0,
            \lut_doutB[1]_input_0_2 ,
            \lut_doutB[1]_input_0_1 ,
            1'b0
         }),
        .out(\lut_doutB[1]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$81[1]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$81[1]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$81[1]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$81[1]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b10100001111100011010101111111011)
    ) \lut_$abc$4367$new_new_n155__  (
        .in({
            1'b0,
            1'b0,
            \lut_$abc$4367$new_new_n155___input_0_2 ,
            1'b0,
            \lut_$abc$4367$new_new_n155___input_0_0 
         }),
        .out(\lut_$abc$4367$new_new_n155___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000001000001010000000000000100)
    ) \lut_doutB[3]  (
        .in({
            \lut_doutB[3]_input_0_4 ,
            \lut_doutB[3]_input_0_3 ,
            1'b0,
            \lut_doutB[3]_input_0_1 ,
            1'b0
         }),
        .out(\lut_doutB[3]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000001010000000000001100)
    ) \lut_doutB[6]  (
        .in({
            \lut_doutB[6]_input_0_4 ,
            1'b0,
            1'b0,
            \lut_doutB[6]_input_0_1 ,
            \lut_doutB[6]_input_0_0 
         }),
        .out(\lut_doutB[6]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01010000111100110101111111110011)
    ) \lut_$abc$4367$new_new_n138__  (
        .in({
            1'b0,
            \lut_$abc$4367$new_new_n138___input_0_3 ,
            \lut_$abc$4367$new_new_n138___input_0_2 ,
            1'b0,
            1'b0
         }),
        .out(\lut_$abc$4367$new_new_n138___output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$81[4]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$81[4]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$81[4]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$81[4]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000001000000010100000100)
    ) \lut_doutB[4]  (
        .in({
            \lut_doutB[4]_input_0_4 ,
            \lut_doutB[4]_input_0_3 ,
            1'b0,
            \lut_doutB[4]_input_0_1 ,
            1'b0
         }),
        .out(\lut_doutB[4]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01010101001111111111111100111111)
    ) \lut_$abc$4367$new_new_n174__  (
        .in({
            1'b0,
            \lut_$abc$4367$new_new_n174___input_0_3 ,
            1'b0,
            \lut_$abc$4367$new_new_n174___input_0_1 ,
            1'b0
         }),
        .out(\lut_$abc$4367$new_new_n174___output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$88[7]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$88[7]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$88[7]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$88[7]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]  (
        .C(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[0]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00011011010111111011101111111111)
    ) \lut_$abc$4367$new_new_n161__  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            \lut_$abc$4367$new_new_n161___input_0_1 ,
            \lut_$abc$4367$new_new_n161___input_0_0 
         }),
        .out(\lut_$abc$4367$new_new_n161___output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]  (
        .C(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:1544:generate_mux$114[1]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$88[2]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$88[2]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$88[2]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$88[2]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01010101001111111111111100111111)
    ) \lut_$abc$4367$new_new_n172__  (
        .in({
            1'b0,
            \lut_$abc$4367$new_new_n172___input_0_3 ,
            1'b0,
            \lut_$abc$4367$new_new_n172___input_0_1 ,
            1'b0
         }),
        .out(\lut_$abc$4367$new_new_n172___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000110000000000100010)
    ) \lut_doutA[7]  (
        .in({
            \lut_doutA[7]_input_0_4 ,
            1'b0,
            \lut_doutA[7]_input_0_2 ,
            1'b0,
            \lut_doutA[7]_input_0_0 
         }),
        .out(\lut_doutA[7]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b10101111000100011010111110111011)
    ) \lut_$abc$4367$new_new_n143__  (
        .in({
            1'b0,
            \lut_$abc$4367$new_new_n143___input_0_3 ,
            1'b0,
            1'b0,
            \lut_$abc$4367$new_new_n143___input_0_0 
         }),
        .out(\lut_$abc$4367$new_new_n143___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000001000000000001010100)
    ) \lut_doutA[2]  (
        .in({
            \lut_doutA[2]_input_0_4 ,
            1'b0,
            \lut_doutA[2]_input_0_2 ,
            \lut_doutA[2]_input_0_1 ,
            1'b0
         }),
        .out(\lut_doutA[2]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000001000000110000000000000010)
    ) \lut_doutA[4]  (
        .in({
            \lut_doutA[4]_input_0_4 ,
            \lut_doutA[4]_input_0_3 ,
            1'b0,
            1'b0,
            \lut_doutA[4]_input_0_0 
         }),
        .out(\lut_doutA[4]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$88[4]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$88[4]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$88[4]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$88[4]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000001000000000001000100010000)
    ) \lut_doutA[6]  (
        .in({
            \lut_doutA[6]_input_0_4 ,
            \lut_doutA[6]_input_0_3 ,
            \lut_doutA[6]_input_0_2 ,
            1'b0,
            1'b0
         }),
        .out(\lut_doutA[6]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00011011010111111011101111111111)
    ) \lut_$abc$4367$new_new_n170__  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            \lut_$abc$4367$new_new_n170___input_0_1 ,
            \lut_$abc$4367$new_new_n170___input_0_0 
         }),
        .out(\lut_$abc$4367$new_new_n170___output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$88[8]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$88[8]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$88[8]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$88[8]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000001000000110000000100000000)
    ) \lut_doutA[8]  (
        .in({
            \lut_doutA[8]_input_0_4 ,
            \lut_doutA[8]_input_0_3 ,
            1'b0,
            1'b0,
            \lut_doutA[8]_input_0_0 
         }),
        .out(\lut_doutA[8]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b11110000010100111111111101010011)
    ) \lut_$abc$4367$new_new_n135__  (
        .in({
            1'b0,
            \lut_$abc$4367$new_new_n135___input_0_3 ,
            \lut_$abc$4367$new_new_n135___input_0_2 ,
            1'b0,
            1'b0
         }),
        .out(\lut_$abc$4367$new_new_n135___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000001)
    ) \lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            \lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_input_0_0 
         }),
        .out(\lut_$abc$1104$auto$rtlil.cc:2392:LogicNot$57_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000001000001110)
    ) \lut_doutB[5]  (
        .in({
            1'b0,
            \lut_doutB[5]_input_0_3 ,
            1'b0,
            \lut_doutB[5]_input_0_1 ,
            \lut_doutB[5]_input_0_0 
         }),
        .out(\lut_doutB[5]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01011111010111110000001111110011)
    ) \lut_$abc$4367$new_new_n165__  (
        .in({
            \lut_$abc$4367$new_new_n165___input_0_4 ,
            1'b0,
            \lut_$abc$4367$new_new_n165___input_0_2 ,
            1'b0,
            1'b0
         }),
        .out(\lut_$abc$4367$new_new_n165___output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$81[8]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$81[8]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$81[8]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$81[8]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2267:execute$82  (
        .C(\dffre_$auto$memory_libmap.cc:2267:execute$82_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2267:execute$82_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2267:execute$82_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2267:execute$82_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2267:execute$82_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$81[0]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$81[0]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$81[0]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$81[0]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000001000000010000001100000000)
    ) \lut_doutB[0]  (
        .in({
            \lut_doutB[0]_input_0_4 ,
            \lut_doutB[0]_input_0_3 ,
            1'b0,
            1'b0,
            \lut_doutB[0]_input_0_0 
         }),
        .out(\lut_doutB[0]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b10101111000100011010111110111011)
    ) \lut_$abc$4367$new_new_n150__  (
        .in({
            1'b0,
            \lut_$abc$4367$new_new_n150___input_0_3 ,
            1'b0,
            1'b0,
            \lut_$abc$4367$new_new_n150___input_0_0 
         }),
        .out(\lut_$abc$4367$new_new_n150___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000001010000000001000100)
    ) \lut_doutB[8]  (
        .in({
            \lut_doutB[8]_input_0_4 ,
            1'b0,
            \lut_doutB[8]_input_0_2 ,
            \lut_doutB[8]_input_0_1 ,
            1'b0
         }),
        .out(\lut_doutB[8]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000001110000000000000100)
    ) \lut_doutB[7]  (
        .in({
            \lut_doutB[7]_input_0_4 ,
            1'b0,
            1'b0,
            \lut_doutB[7]_input_0_1 ,
            \lut_doutB[7]_input_0_0 
         }),
        .out(\lut_doutB[7]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$81[7]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$81[7]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$81[7]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$81[7]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$81[3]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$81[3]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$81[3]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$81[3]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000001)
    ) \lut_$true  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            1'b0
         }),
        .out(\lut_$true_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$81[5]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$81[5]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$81[5]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$81[5]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01010101000011111111111100110011)
    ) \lut_$abc$4367$new_new_n153__  (
        .in({
            \lut_$abc$4367$new_new_n153___input_0_4 ,
            \lut_$abc$4367$new_new_n153___input_0_3 ,
            1'b0,
            1'b0,
            1'b0
         }),
        .out(\lut_$abc$4367$new_new_n153___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000001000000000001010100)
    ) \lut_doutA[0]  (
        .in({
            \lut_doutA[0]_input_0_4 ,
            1'b0,
            \lut_doutA[0]_input_0_2 ,
            \lut_doutA[0]_input_0_1 ,
            1'b0
         }),
        .out(\lut_doutA[0]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b10101010000110111111111100011011)
    ) \lut_$abc$4367$new_new_n167__  (
        .in({
            1'b0,
            \lut_$abc$4367$new_new_n167___input_0_3 ,
            1'b0,
            1'b0,
            \lut_$abc$4367$new_new_n167___input_0_0 
         }),
        .out(\lut_$abc$4367$new_new_n167___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b10101111101011110001000110111011)
    ) \lut_$abc$4367$new_new_n159__  (
        .in({
            \lut_$abc$4367$new_new_n159___input_0_4 ,
            1'b0,
            1'b0,
            1'b0,
            \lut_$abc$4367$new_new_n159___input_0_0 
         }),
        .out(\lut_$abc$4367$new_new_n159___output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2267:execute$89  (
        .C(\dffre_$auto$memory_libmap.cc:2267:execute$89_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2267:execute$89_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2267:execute$89_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2267:execute$89_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2267:execute$89_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$88[0]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$88[0]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$88[0]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$88[0]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01010000010111111111001111110011)
    ) \lut_$abc$4367$new_new_n163__  (
        .in({
            \lut_$abc$4367$new_new_n163___input_0_4 ,
            1'b0,
            \lut_$abc$4367$new_new_n163___input_0_2 ,
            1'b0,
            1'b0
         }),
        .out(\lut_$abc$4367$new_new_n163___output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$88[5]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$88[5]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$88[5]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$88[5]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000011100000100)
    ) \lut_doutA[5]  (
        .in({
            1'b0,
            \lut_doutA[5]_input_0_3 ,
            1'b0,
            \lut_doutA[5]_input_0_1 ,
            \lut_doutA[5]_input_0_0 
         }),
        .out(\lut_doutA[5]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000011100000100)
    ) \lut_doutA[3]  (
        .in({
            1'b0,
            \lut_doutA[3]_input_0_3 ,
            1'b0,
            \lut_doutA[3]_input_0_1 ,
            \lut_doutA[3]_input_0_0 
         }),
        .out(\lut_doutA[3]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$88[3]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$88[3]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$88[3]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$88[3]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000001110000000000000100)
    ) \lut_doutA[1]  (
        .in({
            \lut_doutA[1]_input_0_4 ,
            1'b0,
            1'b0,
            \lut_doutA[1]_input_0_1 ,
            \lut_doutA[1]_input_0_0 
         }),
        .out(\lut_doutA[1]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$88[1]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$88[1]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$88[1]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$88[1]_output_0_0 )
    );

    DFFRE #(
    ) \dffre_$auto$memory_libmap.cc:2266:execute$88[6]  (
        .C(\dffre_$auto$memory_libmap.cc:2266:execute$88[6]_clock_0_0 ),
        .D(\dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_0_0 ),
        .E(\dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_2_0 ),
        .R(\dffre_$auto$memory_libmap.cc:2266:execute$88[6]_input_1_0 ),
        .Q(\dffre_$auto$memory_libmap.cc:2266:execute$88[6]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000001)
    ) \lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            \lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_input_0_0 
         }),
        .out(\lut_$abc$1090$auto$rtlil.cc:2392:LogicNot$69_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01010011000011110101001111111111)
    ) \lut_$abc$4367$new_new_n133__  (
        .in({
            1'b0,
            \lut_$abc$4367$new_new_n133___input_0_3 ,
            \lut_$abc$4367$new_new_n133___input_0_2 ,
            1'b0,
            1'b0
         }),
        .out(\lut_$abc$4367$new_new_n133___output_0_0 )
    );


endmodule
