#!/bin/bash

# This file can be copied into any directory
# For engineering build, remember to execute
#     module load fpga_tools/raptor/build_env
#

INSTALLDIR=/nfs_project/castor/gchen/rapidsilicon
#RELEASE=2023.04
RELEASE=raptor0705a

LM_LICENSE_FILE=$INSTALLDIR/license.txt
export LM_LICENSE_FILE

source $INSTALLDIR/raptor/Raptor/$RELEASE/raptorenv_lin64.sh

raptor --script raptor.tcl



 
