read_verilog -sv /nfs_eda_sw/softwares/Raptor/instl_dir/05_08_2024_09_15_02/share/raptor/sim_models/rapidsilicon/genesis3/FPGA_PRIMITIVES_MODELS/blackbox_models/cell_sim_blackbox.v
plugin -i systemverilog
read_systemverilog -synth  -top lpif -y ../../../../.././rtl -I../../../../.././rtl -I../../../../.. -I/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl +libext+.v+.sv -sv /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/level_delay.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/levelsync.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/ll_auto_sync.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_ctl.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_lpbk.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_lsm.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_pipe_stage.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_pipeline.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_prot_neg.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_full_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_full_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_full_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_full_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_full_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_full_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_half_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_half_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_half_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_half_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_half_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym1_half_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_full_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_full_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_full_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_full_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_full_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_full_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_half_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_half_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_half_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_half_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_half_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_half_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_quarter_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_quarter_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_quarter_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_quarter_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_quarter_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x16_asym2_quarter_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_full_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_full_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_full_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_full_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_full_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_full_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_half_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_half_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_half_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_half_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_half_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x1_asym1_half_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_full_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_full_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_full_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_full_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_full_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_full_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_half_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_half_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_half_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_half_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_half_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x2_asym1_half_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_full_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_full_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_full_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_full_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_full_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_full_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_half_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_half_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_half_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_half_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_half_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_half_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_quarter_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_quarter_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_quarter_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_quarter_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_quarter_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x4_asym2_quarter_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_full_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_full_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_full_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_full_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_full_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_full_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_half_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_half_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_half_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_half_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_half_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym1_half_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_full_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_full_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_full_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_full_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_full_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_full_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_half_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_half_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_half_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_half_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_half_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_half_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_quarter_master_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_quarter_master_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_quarter_master_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_quarter_slave_concat.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_quarter_slave_name.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif_txrx_x8_asym2_quarter_slave_top.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/marker_gen.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/strobe_gen.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/strobe_gen_w_delay.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/syncfifo_reg.sv \
/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/RTL_Benchmarks_Gap_Analysis/lpif/results_dir/.././rtl/lpif.sv \

analyze -top lpif
