// Verilated -*- C++ -*-
// DESCRIPTION: Verilator output: Design internal header
// See Vco_sim_GJC46_edit.h for the primary calling header

#ifndef VERILATED_VCO_SIM_GJC46_EDIT___024ROOT_H_
#define VERILATED_VCO_SIM_GJC46_EDIT___024ROOT_H_  // guard

#include "verilated.h"
#include "verilated_timing.h"


class Vco_sim_GJC46_edit__Syms;

class alignas(VL_CACHE_LINE_BYTES) Vco_sim_GJC46_edit___024root final : public VerilatedModule {
  public:

    // DESIGN SPECIFIC STATE
    // Anonymous structures to workaround compiler member-count bugs
    struct {
        CData/*0:0*/ co_sim_GJC46_edit__DOT__clkGHz;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__reset;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__clk_out_div2;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__clk_vco;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_90;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_180;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_270;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__cdr_clk;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__core_clk;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__clk_out_div2;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__clk_vco;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_90;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_180;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_270;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__cdr_clk;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__core_clk;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__bitslip_ctrl_n;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__data_i;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__enable_n;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__data_i_delay;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_in;
        CData/*7:0*/ co_sim_GJC46_edit__DOT__golden__DOT__wait_pll;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__delay_out;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__LOCK;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__clk_pll;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__pllstart;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__pllstart_ff1;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__pllstart_ff2;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__vcostart;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__vcostart_ff;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__lose_lock;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__clk_out_div3;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__clk_out_div4;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__clk_postdiv;
        CData/*5:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__PLL_DIV_ff;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_delay__DOT__dly_ld_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_delay__DOT__dly_ld_1;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_delay__DOT__dly_adj_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_delay__DOT__dly_adj_1;
        CData/*5:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_delay__DOT__dly_tap_val;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_start;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk0_data_reg;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk0_data_comp;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk90_data_reg;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk90_data_comp;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk180_data_reg;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk180_data_comp;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk270_data_reg;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk270_data_comp;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk0_data_count;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk90_data_count;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk180_data_count;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk270_data_count;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk0_reg_data_count;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk90_reg_data_count;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk180_reg_data_count;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk270_reg_data_count;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__dpa_lock;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__dpa_dout;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__dpa_error;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__dpa_fifo_empty;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__dpa_fifo_full;
    };
    struct {
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__dpa_fifo_dout;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__bitslip_adj_1;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__bitslip_adj_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__bitslip_dout;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__bitslip_shifter_out;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__bitslip_counter;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__word_load_en;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__core_clk_count;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__cdr_core_clk;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__cdr_word_load_en;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__cdr_core_clk_count;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__des_fifo_empty;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__des_fifo_full;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT____Vcellinp__afifo_inst__wr;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__rd_addr;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__wr_addr;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__next_rd_addr;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__next_wr_addr;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__rgray;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__wgray;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__read_empty;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__read_empty;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__CHANNEL_BOND_SYNC_IN;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__core_clk;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__word_load_en;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__core_clk_count;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__fast_clk_sync_out;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__read_en;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__fifo_empty;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__fifo_read_en;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__word_load_en_sync;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__oe_parallel_reg;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__oe_shift_reg;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__fifo1__DOT__full;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__fifo1__DOT__wr_ptr;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__fifo1__DOT__rd_ptr;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_delay__DOT__dly_ld_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_delay__DOT__dly_ld_1;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_delay__DOT__dly_adj_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_delay__DOT__dly_adj_1;
        CData/*5:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_delay__DOT__dly_tap_val;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241161__024abc____VhshGVgqBU6wRRDtA5Ir9Uo4M9yi2GGlyR1rSX1aUOlb;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241161__024abc__024666__024li0_li0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241161__024abc__024666__024li1_li1;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241161__024abc__024666__024li2_li2;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241161__024abc__024666__024li3_li3;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241161__024abc__024666__024li4_li4;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241161__024abc__024666__024li5_li5;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241161__024abc__024666__024li6_li6;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241161__024abc__024666__024li7_li7;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024new_new_n29___05F;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024techmap____VhshMglinVWZCHfXbBuWRBrMeAkj83jPwEwlQ2Lgda8W;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_delay;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_serdes_reg__05b0__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_serdes_reg__05b1__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_serdes_reg__05b2__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_serdes_reg__05b3__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_serdes_reg__05b4__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_serdes_reg__05b5__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_serdes_reg__05b6__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_serdes_reg__05b7__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_serdes_reg__05b8__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_serdes_reg__05b9__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__delay_out;
    };
    struct {
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__wait_pll__05b0__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__wait_pll__05b1__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__wait_pll__05b2__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__wait_pll__05b3__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__wait_pll__05b4__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__wait_pll__05b5__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__wait_pll__05b6__05d;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__wait_pll__05b7__05d;
        CData/*7:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1730__DOT__s3;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1730__DOT__s2;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1730__DOT__s1;
        CData/*7:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1731__DOT__s3;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1731__DOT__s2;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1731__DOT__s1;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1733__DOT__s1;
        CData/*7:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1735__DOT__s3;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1735__DOT__s2;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1735__DOT__s1;
        CData/*7:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1736__DOT__s3;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1736__DOT__s2;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1736__DOT__s1;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1737__DOT__s2;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1737__DOT__s1;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1738__DOT__s1;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1740__DOT__s1;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__LOCK;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__clk_pll;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__pllstart;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__pllstart_ff1;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__pllstart_ff2;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__vcostart;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__vcostart_ff;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__lose_lock;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__clk_out_div3;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__clk_out_div4;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__clk_postdiv;
        CData/*5:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__PLL_DIV_ff;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_delay__DOT__dly_ld_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_delay__DOT__dly_ld_1;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_delay__DOT__dly_adj_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_delay__DOT__dly_adj_1;
        CData/*5:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_delay__DOT__dly_tap_val;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__CHANNEL_BOND_SYNC_IN;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__core_clk;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__word_load_en;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__core_clk_count;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__fast_clk_sync_out;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__read_en;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__fifo_empty;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__fifo_read_en;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__word_load_en_sync;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__oe_parallel_reg;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__oe_shift_reg;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__fifo1__DOT__full;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__fifo1__DOT__wr_ptr;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__fifo1__DOT__rd_ptr;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_delay__DOT__dly_ld_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_delay__DOT__dly_ld_1;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_delay__DOT__dly_adj_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_delay__DOT__dly_adj_1;
        CData/*5:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_delay__DOT__dly_tap_val;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_start;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk0_data_reg;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk0_data_comp;
    };
    struct {
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk90_data_reg;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk90_data_comp;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk180_data_reg;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk180_data_comp;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk270_data_reg;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk270_data_comp;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk0_data_count;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk90_data_count;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk180_data_count;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk270_data_count;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk0_reg_data_count;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk90_reg_data_count;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk180_reg_data_count;
        CData/*1:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk270_reg_data_count;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__dpa_lock;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__dpa_dout;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__dpa_error;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__dpa_fifo_empty;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__dpa_fifo_full;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__dpa_fifo_dout;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__bitslip_adj_1;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__bitslip_adj_0;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__bitslip_dout;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__bitslip_shifter_out;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__bitslip_counter;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__word_load_en;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__core_clk_count;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__cdr_core_clk;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__cdr_word_load_en;
        CData/*3:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__cdr_core_clk_count;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__des_fifo_empty;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__des_fifo_full;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT____Vcellinp__afifo_inst__wr;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__rd_addr;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__wr_addr;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__next_rd_addr;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__next_wr_addr;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__rgray;
        CData/*4:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__wgray;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__read_empty;
        CData/*0:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__read_empty;
        CData/*0:0*/ __VassignWtmp_co_sim_GJC46_edit__DOT__golden__DOT__data_i_delay__0;
        CData/*0:0*/ __Vintraval_h14e37c4a__0;
        CData/*0:0*/ __VassignWtmp_co_sim_GJC46_edit__DOT__golden__DOT__delay_out__0;
        CData/*0:0*/ __Vintraval_h799703ce__0;
        CData/*0:0*/ __VassignWtmp_co_sim_GJC46_edit__DOT__synth_net__DOT__delay_out__0;
        CData/*0:0*/ __Vintraval_h14381aad__0;
        CData/*0:0*/ __VassignWtmp_co_sim_GJC46_edit__DOT__synth_net__DOT__data_i_delay__0;
        CData/*0:0*/ __Vintraval_h8ba0df61__0;
        CData/*7:0*/ __Vdly__co_sim_GJC46_edit__DOT__golden__DOT__wait_pll;
        CData/*0:0*/ __Vdlyvval__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_90__v0;
        CData/*0:0*/ __Vdlyvset__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_90__v0;
        CData/*0:0*/ __Vdlyvval__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_180__v0;
        CData/*0:0*/ __Vdlyvset__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_180__v0;
        CData/*0:0*/ __Vdlyvval__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_270__v0;
        CData/*0:0*/ __Vdlyvset__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_270__v0;
        CData/*3:0*/ __Vdlyvdim0__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvval__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvset__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvset__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvval__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_90__v0;
        CData/*0:0*/ __Vdlyvset__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_90__v0;
        CData/*0:0*/ __Vdlyvval__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_180__v0;
        CData/*0:0*/ __Vdlyvset__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_180__v0;
    };
    struct {
        CData/*0:0*/ __Vdlyvval__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_270__v0;
        CData/*0:0*/ __Vdlyvset__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_270__v0;
        CData/*3:0*/ __Vdlyvdim0__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvval__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvset__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        CData/*0:0*/ __Vdlyvset__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        CData/*0:0*/ __VstlFirstIteration;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__clk_vco__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__clk_vco__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__core_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__reset__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__clkGHz__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__clk_out_div2__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_90__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_180__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_270__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__cdr_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__core_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__clk_out_div2__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_0__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_90__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_180__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_270__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__cdr_clk__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__vcostart_ff__0;
        CData/*0:0*/ __Vtrigprevexpr___TOP__co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__vcostart_ff__0;
        CData/*0:0*/ __VactDidInit;
        CData/*0:0*/ __VactContinue;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__golden__DOT__data_i_serdes;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__golden__DOT__data_i_serdes_reg;
        SData/*11:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__PLL_MULT_ff;
        SData/*8:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__lock_counter;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__bit_shifter;
        SData/*8:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__pll_lock_count;
        SData/*8:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__cdr_pll_lock_count;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__des_shifter;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__des_parallel_reg;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__rd_addr;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__wr_addr;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__next_rd_addr;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__next_wr_addr;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__rgray;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__wgray;
        SData/*8:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__pll_lock_count;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__data_parallel_reg;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__data_shift_reg;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__fifo1__DOT__rd_data_reg;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____Vcellout__input_data_serdes__Q;
        SData/*15:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1730__DOT__s4;
        SData/*15:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT____024abc__0241729__024auto_1735__DOT__s4;
        SData/*11:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__PLL_MULT_ff;
        SData/*8:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__lock_counter;
        SData/*8:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__pll_lock_count;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__data_parallel_reg;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__data_shift_reg;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__fifo1__DOT__rd_data_reg;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__bit_shifter;
        SData/*8:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__pll_lock_count;
        SData/*8:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__cdr_pll_lock_count;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__des_shifter;
        SData/*9:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__des_parallel_reg;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__rd_addr;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__wr_addr;
    };
    struct {
        SData/*10:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__next_rd_addr;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__next_wr_addr;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__rgray;
        SData/*10:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__wgray;
        SData/*9:0*/ __Vdlyvdim0__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        SData/*9:0*/ __Vdlyvval__co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        SData/*9:0*/ __Vdlyvdim0__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        SData/*9:0*/ __Vdlyvval__co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__dual_port_ram__DOT__genblk1__DOT__mem__v0;
        IData/*31:0*/ co_sim_GJC46_edit__DOT__mismatch;
        IData/*31:0*/ co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__div3_count;
        IData/*31:0*/ co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__fifo1__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__div3_count;
        IData/*31:0*/ co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__fifo1__DOT__unnamedblk1__DOT__i;
        IData/*31:0*/ __VactIterCount;
        VlUnpacked<CData/*4:0*/, 2> co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__synchronizer__DOT__wr_sync_register;
        VlUnpacked<CData/*4:0*/, 2> co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__synchronizer__DOT__rd_sync_register;
        VlUnpacked<CData/*0:0*/, 16> co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_dpa__DOT__dual_port_ram__DOT__genblk1__DOT__mem;
        VlUnpacked<SData/*10:0*/, 2> co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__synchronizer__DOT__wr_sync_register;
        VlUnpacked<SData/*10:0*/, 2> co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__synchronizer__DOT__rd_sync_register;
        VlUnpacked<SData/*9:0*/, 1024> co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__afifo_inst__DOT__dual_port_ram__DOT__genblk1__DOT__mem;
        VlUnpacked<SData/*10:0*/, 4> co_sim_GJC46_edit__DOT__golden__DOT__counter_o_serdes__DOT__fifo1__DOT__fifo;
        VlUnpacked<SData/*10:0*/, 4> co_sim_GJC46_edit__DOT__synth_net__DOT__counter_o_serdes__DOT__fifo1__DOT__fifo;
        VlUnpacked<CData/*4:0*/, 2> co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__synchronizer__DOT__wr_sync_register;
        VlUnpacked<CData/*4:0*/, 2> co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__synchronizer__DOT__rd_sync_register;
        VlUnpacked<CData/*0:0*/, 16> co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_dpa__DOT__dual_port_ram__DOT__genblk1__DOT__mem;
        VlUnpacked<SData/*10:0*/, 2> co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__synchronizer__DOT__wr_sync_register;
        VlUnpacked<SData/*10:0*/, 2> co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__synchronizer__DOT__rd_sync_register;
        VlUnpacked<SData/*9:0*/, 1024> co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__afifo_inst__DOT__dual_port_ram__DOT__genblk1__DOT__mem;
        VlUnpacked<CData/*0:0*/, 35> __Vm_traceActivity;
    };
    double co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__t0;
    double co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__t1;
    double co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__ref_period;
    double co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__vco_period;
    double co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__postdiv_period;
    double co_sim_GJC46_edit__DOT__golden__DOT__clk_pll_gen0__DOT__old_ref_period;
    double co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__start_point;
    double co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__end_point;
    double co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__clk_period;
    double co_sim_GJC46_edit__DOT__golden__DOT__input_data_serdes__DOT__period_quarter;
    double co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__t0;
    double co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__t1;
    double co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__ref_period;
    double co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__vco_period;
    double co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__postdiv_period;
    double co_sim_GJC46_edit__DOT__synth_net__DOT__clk_pll_gen0__DOT__old_ref_period;
    double co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__start_point;
    double co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__end_point;
    double co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__clk_period;
    double co_sim_GJC46_edit__DOT__synth_net__DOT__input_data_serdes__DOT__period_quarter;
    VlDelayScheduler __VdlySched;
    VlTriggerScheduler __VtrigSched_h90ee1be2__0;
    VlTriggerScheduler __VtrigSched_h90ee1c21__0;
    VlTriggerScheduler __VtrigSched_h8ca313d9__0;
    VlTriggerScheduler __VtrigSched_h602354a6__0;
    VlTriggerScheduler __VtrigSched_hfece4fe3__0;
    VlTriggerScheduler __VtrigSched_hedea8e0c__0;
    VlTriggerScheduler __VtrigSched_h6dbc2dfd__0;
    VlTriggerScheduler __VtrigSched_h0738c86a__0;
    VlTriggerScheduler __VtrigSched_hc7d82c34__0;
    VlTriggerScheduler __VtrigSched_h73cec462__0;
    VlTriggerVec<1> __VstlTriggered;
    VlTriggerVec<38> __VactTriggered;
    VlTriggerVec<38> __VnbaTriggered;

    // INTERNAL VARIABLES
    Vco_sim_GJC46_edit__Syms* const vlSymsp;

    // CONSTRUCTORS
    Vco_sim_GJC46_edit___024root(Vco_sim_GJC46_edit__Syms* symsp, const char* v__name);
    ~Vco_sim_GJC46_edit___024root();
    VL_UNCOPYABLE(Vco_sim_GJC46_edit___024root);

    // INTERNAL METHODS
    void __Vconfigure(bool first);
};


#endif  // guard
