read_verilog -sv /nfs_eda_sw/softwares/Raptor/instl_dir/07_05_2024_09_15_01/share/raptor/sim_models/rapidsilicon/genesis3/FPGA_PRIMITIVES_MODELS/blackbox_models/cell_sim_blackbox.v
verilog_defines 
read_verilog  -I../../../.././rtl -I../../../../ -I/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/opensource_with_testbench/Matrix-Multiplication-Using-Systolic-Arrays/./rtl  /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/opensource_with_testbench/Matrix-Multiplication-Using-Systolic-Arrays/./rtl/apb_slave.v 
read_verilog  -I../../../.././rtl -I../../../../ -I/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/opensource_with_testbench/Matrix-Multiplication-Using-Systolic-Arrays/./rtl  /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/opensource_with_testbench/Matrix-Multiplication-Using-Systolic-Arrays/./rtl/matmul_calc.v 
read_verilog  -I../../../.././rtl -I../../../../ -I/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/opensource_with_testbench/Matrix-Multiplication-Using-Systolic-Arrays/./rtl  /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/opensource_with_testbench/Matrix-Multiplication-Using-Systolic-Arrays/./rtl/mem.v 
read_verilog  -I../../../.././rtl -I../../../../ -I/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/opensource_with_testbench/Matrix-Multiplication-Using-Systolic-Arrays/./rtl  /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/opensource_with_testbench/Matrix-Multiplication-Using-Systolic-Arrays/./rtl/pe_module.v 
read_verilog  -I../../../.././rtl -I../../../../ -I/nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/opensource_with_testbench/Matrix-Multiplication-Using-Systolic-Arrays/./rtl  /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/os_fpga2/Validation/RTL_testcases/opensource_with_testbench/Matrix-Multiplication-Using-Systolic-Arrays/./rtl/matmul.v 

analyze -top matmul
