-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/07_24_2023_09_15_01/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir ../../../../ /nfs_project/castor/DV/anas/rigel/new_clones/Jira_Testcase/EDA-1806/rtl 
-sv /nfs_project/castor/DV/anas/rigel/new_clones/Jira_Testcase/EDA-1806/rtl/gpio_and.v
-top gpio_and
