create_design i_buf_i_delay_i_ddr_to_sdr
add_design_file i_buf_i_delay_i_ddr_to_sdr.v
set_top_module i_buf_i_delay_i_ddr_to_sdr
add_constraint_file constraints.sdc
add_constraint_file pin_constraints.pin
target_device 1VG28

analyze
synthesize
packing
place
route
sta
bitstream