-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/08_08_2023_09_15_01/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir ../../../../ /nfs_project/gemini/DV/usmanqadir/jira_repo/Jira_Testcase/EDA-1874/ring_counter_wo_constraint 
-vlog2k /nfs_project/gemini/DV/usmanqadir/jira_repo/Jira_Testcase/EDA-1874/ring_counter_wo_constraint/ring_counter.v
-top ring_counter
