create_design accum_output_shifted_rounded_inst
target_device GEMINI_COMPACT_82x68
add_include_path ./rtl
add_library_path ./rtl
add_library_ext .v .sv
add_design_file ./rtl/accum_output_shifted_rounded_inst.v
set_top_module accum_output_shifted_rounded_inst
analyze
synthesize delay
