/* Generated by Yosys 0.38 (git sha1 2b36bfab5, gcc 11.2.1 -fPIC -Os) */

module fabric_gbox_clk_as_data(\$auto_426 , \$auto_427 , \$auto_428 , clk_clk_buf, clk_ibuf, din_ibuf, dout_obuf);
  output \$auto_426 ;
  output \$auto_427 ;
  output \$auto_428 ;
  input clk_clk_buf;
  input clk_ibuf;
  input din_ibuf;
  output dout_obuf;
  wire \$auto_426 ;
  wire \$auto_427 ;
  wire \$auto_428 ;
  (* src = "/nfs_project/castor/DV/Azfar/Rigel/DV/subsystem_level/fabric_verif_env/src/fabric_designs/gbox/gbox_clk_as_data/./gbox_clk_as_data.v:8.8-8.19" *)
  (* src = "/nfs_project/castor/DV/Azfar/Rigel/DV/subsystem_level/fabric_verif_env/src/fabric_designs/gbox/gbox_clk_as_data/./gbox_clk_as_data.v:8.8-8.19" *)
  wire clk_clk_buf;
  (* src = "/nfs_project/castor/DV/Azfar/Rigel/DV/subsystem_level/fabric_verif_env/src/fabric_designs/gbox/gbox_clk_as_data/./gbox_clk_as_data.v:6.8-6.16" *)
  (* src = "/nfs_project/castor/DV/Azfar/Rigel/DV/subsystem_level/fabric_verif_env/src/fabric_designs/gbox/gbox_clk_as_data/./gbox_clk_as_data.v:6.8-6.16" *)
  wire clk_ibuf;
  (* src = "/nfs_project/castor/DV/Azfar/Rigel/DV/subsystem_level/fabric_verif_env/src/fabric_designs/gbox/gbox_clk_as_data/./gbox_clk_as_data.v:7.8-7.16" *)
  (* src = "/nfs_project/castor/DV/Azfar/Rigel/DV/subsystem_level/fabric_verif_env/src/fabric_designs/gbox/gbox_clk_as_data/./gbox_clk_as_data.v:7.8-7.16" *)
  wire din_ibuf;
  (* src = "/nfs_project/castor/DV/Azfar/Rigel/DV/subsystem_level/fabric_verif_env/src/fabric_designs/gbox/gbox_clk_as_data/./gbox_clk_as_data.v:9.8-9.17" *)
  (* src = "/nfs_project/castor/DV/Azfar/Rigel/DV/subsystem_level/fabric_verif_env/src/fabric_designs/gbox/gbox_clk_as_data/./gbox_clk_as_data.v:9.8-9.17" *)
  wire dout_obuf;
  (* init = 1'h0 *)
  (* keep = 32'sh00000001 *)
  (* src = "/nfs_project/castor/DV/Azfar/Rigel/DV/subsystem_level/fabric_verif_env/src/fabric_designs/gbox/gbox_clk_as_data/./gbox_clk_as_data.v:28.7-28.11" *)
  wire temp;
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/ffs_map.v:10.11-10.70" *)
  DFFRE \$abc$188$auto_189  (
    .C(clk_clk_buf),
    .D(din_ibuf),
    .E(1'h1),
    .Q(temp),
    .R(1'h1)
  );
  (* module_not_derived = 32'sh00000001 *)
  (* src = "/nfs_eda_sw/softwares/Raptor/instl_dir/09_16_2024_09_15_01/bin/../share/yosys/rapidsilicon/genesis3/lut_map.v:21.38-21.69" *)
  LUT2 #(
    .INIT_VALUE(4'h8)
  ) \$abc$423$auto_424  (
    .A({ temp, clk_ibuf }),
    .Y(dout_obuf)
  );
  assign \$auto_427  = 1'h1;
  assign \$auto_428  = 1'h1;
  assign \$auto_426  = 1'h1;
endmodule
