create_design i_buf_ds_o_buf_ds
add_design_file i_buf_ds_o_buf_ds.v
set_top_module i_buf_ds_o_buf_ds
add_constraint_file pin_constraints.pin
target_device 1VG28

analyze
synthesize
packing
place
route
sta
bitstream