create_design lpif
target_device 1GVTC
add_include_path ./rtl
add_library_path ./rtl
add_library_ext .v .sv
add_design_file ./rtl/level_delay.sv
add_design_file ./rtl/levelsync.sv
add_design_file ./rtl/ll_auto_sync.sv
add_design_file ./rtl/lpif_ctl.sv
add_design_file ./rtl/lpif_lpbk.sv
add_design_file ./rtl/lpif_lsm.sv
add_design_file ./rtl/lpif_pipe_stage.sv
add_design_file ./rtl/lpif_pipeline.sv
add_design_file ./rtl/lpif_prot_neg.sv
add_design_file ./rtl/lpif_txrx.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_full_master_concat.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_full_master_name.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_full_master_top.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_full_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_full_slave_name.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_full_slave_top.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_half_master_concat.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_half_master_name.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_half_master_top.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_half_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_half_slave_name.sv
add_design_file ./rtl/lpif_txrx_x16_asym1_half_slave_top.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_full_master_concat.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_full_master_name.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_full_master_top.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_full_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_full_slave_name.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_full_slave_top.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_half_master_concat.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_half_master_name.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_half_master_top.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_half_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_half_slave_name.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_half_slave_top.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_quarter_master_concat.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_quarter_master_name.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_quarter_master_top.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_quarter_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_quarter_slave_name.sv
add_design_file ./rtl/lpif_txrx_x16_asym2_quarter_slave_top.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_full_master_concat.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_full_master_name.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_full_master_top.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_full_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_full_slave_name.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_full_slave_top.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_half_master_concat.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_half_master_name.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_half_master_top.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_half_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_half_slave_name.sv
add_design_file ./rtl/lpif_txrx_x1_asym1_half_slave_top.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_full_master_concat.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_full_master_name.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_full_master_top.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_full_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_full_slave_name.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_full_slave_top.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_half_master_concat.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_half_master_name.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_half_master_top.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_half_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_half_slave_name.sv
add_design_file ./rtl/lpif_txrx_x2_asym1_half_slave_top.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_full_master_concat.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_full_master_name.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_full_master_top.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_full_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_full_slave_name.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_full_slave_top.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_half_master_concat.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_half_master_name.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_half_master_top.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_half_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_half_slave_name.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_half_slave_top.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_quarter_master_concat.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_quarter_master_name.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_quarter_master_top.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_quarter_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_quarter_slave_name.sv
add_design_file ./rtl/lpif_txrx_x4_asym2_quarter_slave_top.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_full_master_concat.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_full_master_name.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_full_master_top.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_full_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_full_slave_name.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_full_slave_top.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_half_master_concat.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_half_master_name.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_half_master_top.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_half_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_half_slave_name.sv
add_design_file ./rtl/lpif_txrx_x8_asym1_half_slave_top.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_full_master_concat.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_full_master_name.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_full_master_top.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_full_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_full_slave_name.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_full_slave_top.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_half_master_concat.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_half_master_name.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_half_master_top.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_half_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_half_slave_name.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_half_slave_top.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_quarter_master_concat.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_quarter_master_name.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_quarter_master_top.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_quarter_slave_concat.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_quarter_slave_name.sv
add_design_file ./rtl/lpif_txrx_x8_asym2_quarter_slave_top.sv
add_design_file ./rtl/marker_gen.sv
add_design_file ./rtl/strobe_gen.sv
add_design_file ./rtl/strobe_gen_w_delay.sv
add_design_file ./rtl/syncfifo_reg.sv
add_design_file ./rtl/lpif.sv
set_top_module lpif
add_constraint_file ./raptor_sdc.sdc
analyze
synth_options -effort high
synthesize delay
packing
place
route
sta
power
bitstream 
