#!/bin/bash

# This file can be copied into any directory
# For engineering build, remember to execute
#     module load fpga_tools/raptor/build_env
#
# Engineering build needs to be run on sw02 due to missing libraries
# on the FE servers

INSTALLDIR=/nfs_project/castor/gchen/rapidsilicon
RELEASE=raptor1018

module load fpga_tools/raptor/build_env

LM_LICENSE_FILE=$INSTALLDIR/license.txt
export LM_LICENSE_FILE

source $INSTALLDIR/raptor/Raptor/$RELEASE/raptorenv_lin64.sh

raptor --script raptor.tcl



 
