create_design pll_4_clocks_posedge
add_design_file pll_4_clocks_posedge.v
set_top_module pll_4_clocks_posedge
# add_constraint_file constraints.sdc
add_constraint_file pin_constraints.pin
target_device 1VG28

analyze
synthesize
packing
place
route
sta
bitstream
