-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/07_02_2023_09_15_02/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir ../../../.././rtl ../../../../ /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/bitstream_simulation_new/test/design3_5_5_top/./rtl 
-vlog-libdir ../../../.././rtl 
-vlog-libext .v
-vlog-libext .sv
-vlog-define 
-vlog2k /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/bitstream_simulation_new/test/design3_5_5_top/./rtl/design3_5_5_top.v
-top design3_5_5_top
