-sv2009 /home/users/bilal.malik/Downloads/raptor_installation/Raptor/2023.07/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir /home/users/bilal.malik/Downloads/raptor_installation/NewFolder 
-vlog2k /home/users/bilal.malik/Downloads/raptor_installation/NewFolder/alu.v
