//Verilog generated by VPR  from post-place-and-route implementation
module ring_counter (
    input \clock0 ,
    input \reset ,
    input \lr ,
    input \loopback_en ,
    input \counter_in[0] ,
    input \counter_in[1] ,
    input \counter_in[2] ,
    input \counter_in[3] ,
    input \counter_in[4] ,
    input \counter_in[5] ,
    input \counter_in[6] ,
    input \counter_in[7] ,
    input \counter_in[8] ,
    input \counter_in[9] ,
    input \counter_in[10] ,
    input \counter_in[11] ,
    input \counter_in[12] ,
    input \counter_in[13] ,
    input \counter_in[14] ,
    input \counter_in[15] ,
    output \loopback_error ,
    output \out[0] ,
    output \out[1] ,
    output \out[2] ,
    output \out[3] ,
    output \out[4] ,
    output \out[5] ,
    output \out[6] ,
    output \out[7] ,
    output \out[8] ,
    output \out[9] ,
    output \out[10] ,
    output \out[11] ,
    output \out[12] ,
    output \out[13] ,
    output \out[14] ,
    output \out[15] 
);

    //Wires
    wire \clock0_output_0_0 ;
    wire \reset_output_0_0 ;
    wire \lr_output_0_0 ;
    wire \loopback_en_output_0_0 ;
    wire \counter_in[0]_output_0_0 ;
    wire \counter_in[1]_output_0_0 ;
    wire \counter_in[2]_output_0_0 ;
    wire \counter_in[3]_output_0_0 ;
    wire \counter_in[4]_output_0_0 ;
    wire \counter_in[5]_output_0_0 ;
    wire \counter_in[6]_output_0_0 ;
    wire \counter_in[7]_output_0_0 ;
    wire \counter_in[8]_output_0_0 ;
    wire \counter_in[9]_output_0_0 ;
    wire \counter_in[10]_output_0_0 ;
    wire \counter_in[11]_output_0_0 ;
    wire \counter_in[12]_output_0_0 ;
    wire \counter_in[13]_output_0_0 ;
    wire \counter_in[14]_output_0_0 ;
    wire \counter_in[15]_output_0_0 ;
    wire \lut_loopback_error_output_0_0 ;
    wire \dffre_out[0]_output_0_0 ;
    wire \dffre_out[1]_output_0_0 ;
    wire \dffre_out[2]_output_0_0 ;
    wire \dffre_out[3]_output_0_0 ;
    wire \dffre_out[4]_output_0_0 ;
    wire \dffre_out[5]_output_0_0 ;
    wire \dffre_out[6]_output_0_0 ;
    wire \dffre_out[7]_output_0_0 ;
    wire \dffre_out[8]_output_0_0 ;
    wire \dffre_out[9]_output_0_0 ;
    wire \dffre_out[10]_output_0_0 ;
    wire \dffre_out[11]_output_0_0 ;
    wire \dffre_out[12]_output_0_0 ;
    wire \dffre_out[13]_output_0_0 ;
    wire \dffre_out[14]_output_0_0 ;
    wire \dffre_out[15]_output_0_0 ;
    wire \lut_$true_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li12_li12_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li07_li07_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li09_li09_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li14_li14_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li15_li15_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li05_li05_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li03_li03_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li01_li01_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li00_li00_output_0_0 ;
    wire \lut_$abc$1686$new_new_n63___output_0_0 ;
    wire \lut_$abc$1686$new_new_n64___output_0_0 ;
    wire \lut_$abc$1686$new_new_n65___output_0_0 ;
    wire \lut_$abc$1686$new_new_n66___output_0_0 ;
    wire \lut_$abc$1686$new_new_n67___output_0_0 ;
    wire \lut_$abc$1686$new_new_n68___output_0_0 ;
    wire \lut_$abc$1686$new_new_n69___output_0_0 ;
    wire \lut_$abc$1686$new_new_n70___output_0_0 ;
    wire \lut_$abc$1686$abc$630$li02_li02_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li04_li04_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li06_li06_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li13_li13_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li10_li10_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li11_li11_output_0_0 ;
    wire \lut_$abc$1686$abc$630$li08_li08_output_0_0 ;
    wire \dffre_out[8]_clock_0_0 ;
    wire \dffre_out[10]_clock_0_0 ;
    wire \dffre_out[9]_clock_0_0 ;
    wire \dffre_out[11]_clock_0_0 ;
    wire \dffre_out[2]_clock_0_0 ;
    wire \dffre_out[0]_clock_0_0 ;
    wire \dffre_out[4]_clock_0_0 ;
    wire \dffre_out[6]_clock_0_0 ;
    wire \dffre_out[15]_clock_0_0 ;
    wire \dffre_out[13]_clock_0_0 ;
    wire \dffre_out[12]_clock_0_0 ;
    wire \dffre_out[14]_clock_0_0 ;
    wire \dffre_out[1]_clock_0_0 ;
    wire \dffre_out[3]_clock_0_0 ;
    wire \dffre_out[5]_clock_0_0 ;
    wire \dffre_out[7]_clock_0_0 ;
    wire \lut_$abc$1686$abc$630$li08_li08_input_0_2 ;
    wire \lut_$abc$1686$abc$630$li10_li10_input_0_2 ;
    wire \lut_$abc$1686$abc$630$li09_li09_input_0_4 ;
    wire \lut_$abc$1686$abc$630$li11_li11_input_0_4 ;
    wire \lut_$abc$1686$abc$630$li02_li02_input_0_1 ;
    wire \lut_$abc$1686$abc$630$li00_li00_input_0_1 ;
    wire \lut_$abc$1686$abc$630$li04_li04_input_0_1 ;
    wire \lut_$abc$1686$abc$630$li06_li06_input_0_1 ;
    wire \lut_$abc$1686$abc$630$li15_li15_input_0_2 ;
    wire \lut_$abc$1686$abc$630$li13_li13_input_0_2 ;
    wire \lut_$abc$1686$abc$630$li12_li12_input_0_4 ;
    wire \lut_$abc$1686$abc$630$li14_li14_input_0_4 ;
    wire \lut_$abc$1686$abc$630$li01_li01_input_0_3 ;
    wire \lut_$abc$1686$abc$630$li03_li03_input_0_3 ;
    wire \lut_$abc$1686$abc$630$li05_li05_input_0_4 ;
    wire \lut_$abc$1686$abc$630$li07_li07_input_0_4 ;
    wire \lut_$abc$1686$abc$630$li08_li08_input_0_3 ;
    wire \lut_$abc$1686$abc$630$li10_li10_input_0_3 ;
    wire \lut_$abc$1686$abc$630$li09_li09_input_0_1 ;
    wire \lut_$abc$1686$abc$630$li11_li11_input_0_1 ;
    wire \lut_$abc$1686$abc$630$li02_li02_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li00_li00_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li04_li04_input_0_3 ;
    wire \lut_$abc$1686$abc$630$li06_li06_input_0_3 ;
    wire \lut_$abc$1686$abc$630$li15_li15_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li13_li13_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li12_li12_input_0_2 ;
    wire \lut_$abc$1686$abc$630$li14_li14_input_0_2 ;
    wire \lut_$abc$1686$abc$630$li01_li01_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li03_li03_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li05_li05_input_0_1 ;
    wire \lut_$abc$1686$abc$630$li07_li07_input_0_1 ;
    wire \lut_loopback_error_input_0_2 ;
    wire \lut_$abc$1686$new_new_n66___input_0_4 ;
    wire \lut_$abc$1686$new_new_n69___input_0_3 ;
    wire \lut_$abc$1686$new_new_n70___input_0_0 ;
    wire \lut_$abc$1686$new_new_n65___input_0_0 ;
    wire \lut_$abc$1686$new_new_n67___input_0_3 ;
    wire \lut_$abc$1686$new_new_n63___input_0_4 ;
    wire \lut_$abc$1686$new_new_n64___input_0_0 ;
    wire \lut_$abc$1686$new_new_n68___input_0_1 ;
    wire \lut_$abc$1686$new_new_n67___input_0_1 ;
    wire \lut_$abc$1686$new_new_n65___input_0_1 ;
    wire \lut_$abc$1686$new_new_n70___input_0_1 ;
    wire \lut_$abc$1686$new_new_n66___input_0_2 ;
    wire \lut_$abc$1686$new_new_n68___input_0_4 ;
    wire \lut_$abc$1686$new_new_n64___input_0_2 ;
    wire \lut_$abc$1686$new_new_n63___input_0_3 ;
    wire \lut_$abc$1686$new_new_n69___input_0_1 ;
    wire \loopback_error_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li15_li15_input_0_1 ;
    wire \lut_$abc$1686$abc$630$li01_li01_input_0_4 ;
    wire \lut_$abc$1686$new_new_n66___input_0_3 ;
    wire \out[0]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li02_li02_input_0_4 ;
    wire \lut_$abc$1686$abc$630$li00_li00_input_0_4 ;
    wire \lut_$abc$1686$new_new_n69___input_0_4 ;
    wire \out[1]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li01_li01_input_0_1 ;
    wire \lut_$abc$1686$abc$630$li03_li03_input_0_1 ;
    wire \lut_$abc$1686$new_new_n70___input_0_2 ;
    wire \out[2]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li02_li02_input_0_2 ;
    wire \lut_$abc$1686$abc$630$li04_li04_input_0_4 ;
    wire \lut_$abc$1686$new_new_n65___input_0_2 ;
    wire \out[3]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li03_li03_input_0_2 ;
    wire \lut_$abc$1686$abc$630$li05_li05_input_0_3 ;
    wire \lut_$abc$1686$new_new_n67___input_0_2 ;
    wire \out[4]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li04_li04_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li06_li06_input_0_0 ;
    wire \lut_$abc$1686$new_new_n63___input_0_2 ;
    wire \out[5]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li05_li05_input_0_2 ;
    wire \lut_$abc$1686$abc$630$li07_li07_input_0_2 ;
    wire \lut_$abc$1686$new_new_n64___input_0_1 ;
    wire \out[6]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li08_li08_input_0_4 ;
    wire \lut_$abc$1686$abc$630$li06_li06_input_0_2 ;
    wire \lut_$abc$1686$new_new_n68___input_0_0 ;
    wire \out[7]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li09_li09_input_0_2 ;
    wire \lut_$abc$1686$abc$630$li07_li07_input_0_0 ;
    wire \lut_$abc$1686$new_new_n67___input_0_4 ;
    wire \out[8]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li08_li08_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li10_li10_input_0_0 ;
    wire \lut_$abc$1686$new_new_n65___input_0_4 ;
    wire \out[9]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li09_li09_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li11_li11_input_0_0 ;
    wire \lut_$abc$1686$new_new_n70___input_0_3 ;
    wire \out[10]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li10_li10_input_0_1 ;
    wire \lut_$abc$1686$abc$630$li12_li12_input_0_1 ;
    wire \lut_$abc$1686$new_new_n66___input_0_1 ;
    wire \out[11]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li11_li11_input_0_3 ;
    wire \lut_$abc$1686$abc$630$li13_li13_input_0_3 ;
    wire \lut_$abc$1686$new_new_n68___input_0_3 ;
    wire \out[12]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li12_li12_input_0_3 ;
    wire \lut_$abc$1686$abc$630$li14_li14_input_0_3 ;
    wire \lut_$abc$1686$new_new_n64___input_0_4 ;
    wire \out[13]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li15_li15_input_0_4 ;
    wire \lut_$abc$1686$abc$630$li13_li13_input_0_4 ;
    wire \lut_$abc$1686$new_new_n63___input_0_1 ;
    wire \out[14]_input_0_0 ;
    wire \lut_$abc$1686$abc$630$li00_li00_input_0_3 ;
    wire \lut_$abc$1686$abc$630$li14_li14_input_0_0 ;
    wire \lut_$abc$1686$new_new_n69___input_0_0 ;
    wire \out[15]_input_0_0 ;
    wire \dffre_out[8]_input_1_0 ;
    wire \dffre_out[8]_input_2_0 ;
    wire \dffre_out[10]_input_1_0 ;
    wire \dffre_out[10]_input_2_0 ;
    wire \dffre_out[9]_input_1_0 ;
    wire \dffre_out[9]_input_2_0 ;
    wire \dffre_out[11]_input_1_0 ;
    wire \dffre_out[11]_input_2_0 ;
    wire \dffre_out[2]_input_1_0 ;
    wire \dffre_out[2]_input_2_0 ;
    wire \dffre_out[0]_input_1_0 ;
    wire \dffre_out[0]_input_2_0 ;
    wire \dffre_out[4]_input_1_0 ;
    wire \dffre_out[4]_input_2_0 ;
    wire \dffre_out[6]_input_1_0 ;
    wire \dffre_out[6]_input_2_0 ;
    wire \dffre_out[15]_input_1_0 ;
    wire \dffre_out[15]_input_2_0 ;
    wire \dffre_out[13]_input_1_0 ;
    wire \dffre_out[13]_input_2_0 ;
    wire \dffre_out[12]_input_1_0 ;
    wire \dffre_out[12]_input_2_0 ;
    wire \dffre_out[14]_input_1_0 ;
    wire \dffre_out[14]_input_2_0 ;
    wire \dffre_out[1]_input_1_0 ;
    wire \dffre_out[1]_input_2_0 ;
    wire \dffre_out[3]_input_1_0 ;
    wire \dffre_out[3]_input_2_0 ;
    wire \dffre_out[5]_input_1_0 ;
    wire \dffre_out[5]_input_2_0 ;
    wire \dffre_out[7]_input_1_0 ;
    wire \dffre_out[7]_input_2_0 ;
    wire \dffre_out[12]_input_0_0 ;
    wire \dffre_out[7]_input_0_0 ;
    wire \dffre_out[9]_input_0_0 ;
    wire \dffre_out[14]_input_0_0 ;
    wire \dffre_out[15]_input_0_0 ;
    wire \dffre_out[5]_input_0_0 ;
    wire \dffre_out[3]_input_0_0 ;
    wire \dffre_out[1]_input_0_0 ;
    wire \dffre_out[0]_input_0_0 ;
    wire \lut_$abc$1686$new_new_n64___input_0_3 ;
    wire \lut_loopback_error_input_0_1 ;
    wire \lut_$abc$1686$new_new_n66___input_0_0 ;
    wire \lut_loopback_error_input_0_0 ;
    wire \lut_$abc$1686$new_new_n68___input_0_2 ;
    wire \lut_loopback_error_input_0_3 ;
    wire \lut_$abc$1686$new_new_n70___input_0_4 ;
    wire \lut_loopback_error_input_0_4 ;
    wire \dffre_out[2]_input_0_0 ;
    wire \dffre_out[4]_input_0_0 ;
    wire \dffre_out[6]_input_0_0 ;
    wire \dffre_out[13]_input_0_0 ;
    wire \dffre_out[10]_input_0_0 ;
    wire \dffre_out[11]_input_0_0 ;
    wire \dffre_out[8]_input_0_0 ;

    //IO assignments
    assign \loopback_error  = \loopback_error_input_0_0 ;
    assign \out[0]  = \out[0]_input_0_0 ;
    assign \out[1]  = \out[1]_input_0_0 ;
    assign \out[2]  = \out[2]_input_0_0 ;
    assign \out[3]  = \out[3]_input_0_0 ;
    assign \out[4]  = \out[4]_input_0_0 ;
    assign \out[5]  = \out[5]_input_0_0 ;
    assign \out[6]  = \out[6]_input_0_0 ;
    assign \out[7]  = \out[7]_input_0_0 ;
    assign \out[8]  = \out[8]_input_0_0 ;
    assign \out[9]  = \out[9]_input_0_0 ;
    assign \out[10]  = \out[10]_input_0_0 ;
    assign \out[11]  = \out[11]_input_0_0 ;
    assign \out[12]  = \out[12]_input_0_0 ;
    assign \out[13]  = \out[13]_input_0_0 ;
    assign \out[14]  = \out[14]_input_0_0 ;
    assign \out[15]  = \out[15]_input_0_0 ;
    assign \clock0_output_0_0  = \clock0 ;
    assign \reset_output_0_0  = \reset ;
    assign \lr_output_0_0  = \lr ;
    assign \loopback_en_output_0_0  = \loopback_en ;
    assign \counter_in[0]_output_0_0  = \counter_in[0] ;
    assign \counter_in[1]_output_0_0  = \counter_in[1] ;
    assign \counter_in[2]_output_0_0  = \counter_in[2] ;
    assign \counter_in[3]_output_0_0  = \counter_in[3] ;
    assign \counter_in[4]_output_0_0  = \counter_in[4] ;
    assign \counter_in[5]_output_0_0  = \counter_in[5] ;
    assign \counter_in[6]_output_0_0  = \counter_in[6] ;
    assign \counter_in[7]_output_0_0  = \counter_in[7] ;
    assign \counter_in[8]_output_0_0  = \counter_in[8] ;
    assign \counter_in[9]_output_0_0  = \counter_in[9] ;
    assign \counter_in[10]_output_0_0  = \counter_in[10] ;
    assign \counter_in[11]_output_0_0  = \counter_in[11] ;
    assign \counter_in[12]_output_0_0  = \counter_in[12] ;
    assign \counter_in[13]_output_0_0  = \counter_in[13] ;
    assign \counter_in[14]_output_0_0  = \counter_in[14] ;
    assign \counter_in[15]_output_0_0  = \counter_in[15] ;

    //Interconnect
    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[8]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[8]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[10]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[10]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[9]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[9]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[11]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[11]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[2]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[2]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[0]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[0]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[4]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[4]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[6]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[6]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[15]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[15]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[13]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[13]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[12]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[12]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[14]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[14]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[1]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[1]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[3]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[3]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[5]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[5]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_clock0_output_0_0_to_dffre_out[7]_clock_0_0  (
        .datain(\clock0_output_0_0 ),
        .dataout(\dffre_out[7]_clock_0_0 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li08_li08_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li08_li08_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li10_li10_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li10_li10_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li09_li09_input_0_4  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li09_li09_input_0_4 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li11_li11_input_0_4  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li11_li11_input_0_4 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li02_li02_input_0_1  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li02_li02_input_0_1 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li00_li00_input_0_1  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li00_li00_input_0_1 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li04_li04_input_0_1  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li04_li04_input_0_1 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li06_li06_input_0_1  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li06_li06_input_0_1 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li15_li15_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li15_li15_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li13_li13_input_0_2  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li13_li13_input_0_2 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li12_li12_input_0_4  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li12_li12_input_0_4 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li14_li14_input_0_4  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li14_li14_input_0_4 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li01_li01_input_0_3  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li01_li01_input_0_3 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li03_li03_input_0_3  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li03_li03_input_0_3 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li05_li05_input_0_4  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li05_li05_input_0_4 )
    );

    fpga_interconnect \routing_segment_reset_output_0_0_to_lut_$abc$1686$abc$630$li07_li07_input_0_4  (
        .datain(\reset_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li07_li07_input_0_4 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li08_li08_input_0_3  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li08_li08_input_0_3 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li10_li10_input_0_3  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li10_li10_input_0_3 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li09_li09_input_0_1  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li09_li09_input_0_1 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li11_li11_input_0_1  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li11_li11_input_0_1 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li02_li02_input_0_0  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li02_li02_input_0_0 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li00_li00_input_0_0  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li00_li00_input_0_0 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li04_li04_input_0_3  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li04_li04_input_0_3 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li06_li06_input_0_3  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li06_li06_input_0_3 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li15_li15_input_0_0  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li15_li15_input_0_0 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li13_li13_input_0_0  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li13_li13_input_0_0 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li12_li12_input_0_2  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li12_li12_input_0_2 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li14_li14_input_0_2  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li14_li14_input_0_2 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li01_li01_input_0_0  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li01_li01_input_0_0 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li03_li03_input_0_0  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li03_li03_input_0_0 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li05_li05_input_0_1  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li05_li05_input_0_1 )
    );

    fpga_interconnect \routing_segment_lr_output_0_0_to_lut_$abc$1686$abc$630$li07_li07_input_0_1  (
        .datain(\lr_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li07_li07_input_0_1 )
    );

    fpga_interconnect \routing_segment_loopback_en_output_0_0_to_lut_loopback_error_input_0_2  (
        .datain(\loopback_en_output_0_0 ),
        .dataout(\lut_loopback_error_input_0_2 )
    );

    fpga_interconnect \routing_segment_counter_in[0]_output_0_0_to_lut_$abc$1686$new_new_n66___input_0_4  (
        .datain(\counter_in[0]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n66___input_0_4 )
    );

    fpga_interconnect \routing_segment_counter_in[1]_output_0_0_to_lut_$abc$1686$new_new_n69___input_0_3  (
        .datain(\counter_in[1]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n69___input_0_3 )
    );

    fpga_interconnect \routing_segment_counter_in[2]_output_0_0_to_lut_$abc$1686$new_new_n70___input_0_0  (
        .datain(\counter_in[2]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n70___input_0_0 )
    );

    fpga_interconnect \routing_segment_counter_in[3]_output_0_0_to_lut_$abc$1686$new_new_n65___input_0_0  (
        .datain(\counter_in[3]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n65___input_0_0 )
    );

    fpga_interconnect \routing_segment_counter_in[4]_output_0_0_to_lut_$abc$1686$new_new_n67___input_0_3  (
        .datain(\counter_in[4]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n67___input_0_3 )
    );

    fpga_interconnect \routing_segment_counter_in[5]_output_0_0_to_lut_$abc$1686$new_new_n63___input_0_4  (
        .datain(\counter_in[5]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n63___input_0_4 )
    );

    fpga_interconnect \routing_segment_counter_in[6]_output_0_0_to_lut_$abc$1686$new_new_n64___input_0_0  (
        .datain(\counter_in[6]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n64___input_0_0 )
    );

    fpga_interconnect \routing_segment_counter_in[7]_output_0_0_to_lut_$abc$1686$new_new_n68___input_0_1  (
        .datain(\counter_in[7]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n68___input_0_1 )
    );

    fpga_interconnect \routing_segment_counter_in[8]_output_0_0_to_lut_$abc$1686$new_new_n67___input_0_1  (
        .datain(\counter_in[8]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n67___input_0_1 )
    );

    fpga_interconnect \routing_segment_counter_in[9]_output_0_0_to_lut_$abc$1686$new_new_n65___input_0_1  (
        .datain(\counter_in[9]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n65___input_0_1 )
    );

    fpga_interconnect \routing_segment_counter_in[10]_output_0_0_to_lut_$abc$1686$new_new_n70___input_0_1  (
        .datain(\counter_in[10]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n70___input_0_1 )
    );

    fpga_interconnect \routing_segment_counter_in[11]_output_0_0_to_lut_$abc$1686$new_new_n66___input_0_2  (
        .datain(\counter_in[11]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n66___input_0_2 )
    );

    fpga_interconnect \routing_segment_counter_in[12]_output_0_0_to_lut_$abc$1686$new_new_n68___input_0_4  (
        .datain(\counter_in[12]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n68___input_0_4 )
    );

    fpga_interconnect \routing_segment_counter_in[13]_output_0_0_to_lut_$abc$1686$new_new_n64___input_0_2  (
        .datain(\counter_in[13]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n64___input_0_2 )
    );

    fpga_interconnect \routing_segment_counter_in[14]_output_0_0_to_lut_$abc$1686$new_new_n63___input_0_3  (
        .datain(\counter_in[14]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n63___input_0_3 )
    );

    fpga_interconnect \routing_segment_counter_in[15]_output_0_0_to_lut_$abc$1686$new_new_n69___input_0_1  (
        .datain(\counter_in[15]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n69___input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_loopback_error_output_0_0_to_loopback_error_input_0_0  (
        .datain(\lut_loopback_error_output_0_0 ),
        .dataout(\loopback_error_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[0]_output_0_0_to_lut_$abc$1686$abc$630$li15_li15_input_0_1  (
        .datain(\dffre_out[0]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li15_li15_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_out[0]_output_0_0_to_lut_$abc$1686$abc$630$li01_li01_input_0_4  (
        .datain(\dffre_out[0]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li01_li01_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_out[0]_output_0_0_to_lut_$abc$1686$new_new_n66___input_0_3  (
        .datain(\dffre_out[0]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n66___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_out[0]_output_0_0_to_out[0]_input_0_0  (
        .datain(\dffre_out[0]_output_0_0 ),
        .dataout(\out[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[1]_output_0_0_to_lut_$abc$1686$abc$630$li02_li02_input_0_4  (
        .datain(\dffre_out[1]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li02_li02_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_out[1]_output_0_0_to_lut_$abc$1686$abc$630$li00_li00_input_0_4  (
        .datain(\dffre_out[1]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li00_li00_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_out[1]_output_0_0_to_lut_$abc$1686$new_new_n69___input_0_4  (
        .datain(\dffre_out[1]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n69___input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_out[1]_output_0_0_to_out[1]_input_0_0  (
        .datain(\dffre_out[1]_output_0_0 ),
        .dataout(\out[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[2]_output_0_0_to_lut_$abc$1686$abc$630$li01_li01_input_0_1  (
        .datain(\dffre_out[2]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li01_li01_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_out[2]_output_0_0_to_lut_$abc$1686$abc$630$li03_li03_input_0_1  (
        .datain(\dffre_out[2]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li03_li03_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_out[2]_output_0_0_to_lut_$abc$1686$new_new_n70___input_0_2  (
        .datain(\dffre_out[2]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n70___input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_out[2]_output_0_0_to_out[2]_input_0_0  (
        .datain(\dffre_out[2]_output_0_0 ),
        .dataout(\out[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[3]_output_0_0_to_lut_$abc$1686$abc$630$li02_li02_input_0_2  (
        .datain(\dffre_out[3]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li02_li02_input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_out[3]_output_0_0_to_lut_$abc$1686$abc$630$li04_li04_input_0_4  (
        .datain(\dffre_out[3]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li04_li04_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_out[3]_output_0_0_to_lut_$abc$1686$new_new_n65___input_0_2  (
        .datain(\dffre_out[3]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n65___input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_out[3]_output_0_0_to_out[3]_input_0_0  (
        .datain(\dffre_out[3]_output_0_0 ),
        .dataout(\out[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[4]_output_0_0_to_lut_$abc$1686$abc$630$li03_li03_input_0_2  (
        .datain(\dffre_out[4]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li03_li03_input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_out[4]_output_0_0_to_lut_$abc$1686$abc$630$li05_li05_input_0_3  (
        .datain(\dffre_out[4]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li05_li05_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_out[4]_output_0_0_to_lut_$abc$1686$new_new_n67___input_0_2  (
        .datain(\dffre_out[4]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n67___input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_out[4]_output_0_0_to_out[4]_input_0_0  (
        .datain(\dffre_out[4]_output_0_0 ),
        .dataout(\out[4]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[5]_output_0_0_to_lut_$abc$1686$abc$630$li04_li04_input_0_0  (
        .datain(\dffre_out[5]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li04_li04_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[5]_output_0_0_to_lut_$abc$1686$abc$630$li06_li06_input_0_0  (
        .datain(\dffre_out[5]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li06_li06_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[5]_output_0_0_to_lut_$abc$1686$new_new_n63___input_0_2  (
        .datain(\dffre_out[5]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n63___input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_out[5]_output_0_0_to_out[5]_input_0_0  (
        .datain(\dffre_out[5]_output_0_0 ),
        .dataout(\out[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[6]_output_0_0_to_lut_$abc$1686$abc$630$li05_li05_input_0_2  (
        .datain(\dffre_out[6]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li05_li05_input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_out[6]_output_0_0_to_lut_$abc$1686$abc$630$li07_li07_input_0_2  (
        .datain(\dffre_out[6]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li07_li07_input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_out[6]_output_0_0_to_lut_$abc$1686$new_new_n64___input_0_1  (
        .datain(\dffre_out[6]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n64___input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_out[6]_output_0_0_to_out[6]_input_0_0  (
        .datain(\dffre_out[6]_output_0_0 ),
        .dataout(\out[6]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[7]_output_0_0_to_lut_$abc$1686$abc$630$li08_li08_input_0_4  (
        .datain(\dffre_out[7]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li08_li08_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_out[7]_output_0_0_to_lut_$abc$1686$abc$630$li06_li06_input_0_2  (
        .datain(\dffre_out[7]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li06_li06_input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_out[7]_output_0_0_to_lut_$abc$1686$new_new_n68___input_0_0  (
        .datain(\dffre_out[7]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n68___input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[7]_output_0_0_to_out[7]_input_0_0  (
        .datain(\dffre_out[7]_output_0_0 ),
        .dataout(\out[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[8]_output_0_0_to_lut_$abc$1686$abc$630$li09_li09_input_0_2  (
        .datain(\dffre_out[8]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li09_li09_input_0_2 )
    );

    fpga_interconnect \routing_segment_dffre_out[8]_output_0_0_to_lut_$abc$1686$abc$630$li07_li07_input_0_0  (
        .datain(\dffre_out[8]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li07_li07_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[8]_output_0_0_to_lut_$abc$1686$new_new_n67___input_0_4  (
        .datain(\dffre_out[8]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n67___input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_out[8]_output_0_0_to_out[8]_input_0_0  (
        .datain(\dffre_out[8]_output_0_0 ),
        .dataout(\out[8]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[9]_output_0_0_to_lut_$abc$1686$abc$630$li08_li08_input_0_0  (
        .datain(\dffre_out[9]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li08_li08_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[9]_output_0_0_to_lut_$abc$1686$abc$630$li10_li10_input_0_0  (
        .datain(\dffre_out[9]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li10_li10_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[9]_output_0_0_to_lut_$abc$1686$new_new_n65___input_0_4  (
        .datain(\dffre_out[9]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n65___input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_out[9]_output_0_0_to_out[9]_input_0_0  (
        .datain(\dffre_out[9]_output_0_0 ),
        .dataout(\out[9]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[10]_output_0_0_to_lut_$abc$1686$abc$630$li09_li09_input_0_0  (
        .datain(\dffre_out[10]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li09_li09_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[10]_output_0_0_to_lut_$abc$1686$abc$630$li11_li11_input_0_0  (
        .datain(\dffre_out[10]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li11_li11_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[10]_output_0_0_to_lut_$abc$1686$new_new_n70___input_0_3  (
        .datain(\dffre_out[10]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n70___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_out[10]_output_0_0_to_out[10]_input_0_0  (
        .datain(\dffre_out[10]_output_0_0 ),
        .dataout(\out[10]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[11]_output_0_0_to_lut_$abc$1686$abc$630$li10_li10_input_0_1  (
        .datain(\dffre_out[11]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li10_li10_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_out[11]_output_0_0_to_lut_$abc$1686$abc$630$li12_li12_input_0_1  (
        .datain(\dffre_out[11]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li12_li12_input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_out[11]_output_0_0_to_lut_$abc$1686$new_new_n66___input_0_1  (
        .datain(\dffre_out[11]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n66___input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_out[11]_output_0_0_to_out[11]_input_0_0  (
        .datain(\dffre_out[11]_output_0_0 ),
        .dataout(\out[11]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[12]_output_0_0_to_lut_$abc$1686$abc$630$li11_li11_input_0_3  (
        .datain(\dffre_out[12]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li11_li11_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_out[12]_output_0_0_to_lut_$abc$1686$abc$630$li13_li13_input_0_3  (
        .datain(\dffre_out[12]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li13_li13_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_out[12]_output_0_0_to_lut_$abc$1686$new_new_n68___input_0_3  (
        .datain(\dffre_out[12]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n68___input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_out[12]_output_0_0_to_out[12]_input_0_0  (
        .datain(\dffre_out[12]_output_0_0 ),
        .dataout(\out[12]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[13]_output_0_0_to_lut_$abc$1686$abc$630$li12_li12_input_0_3  (
        .datain(\dffre_out[13]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li12_li12_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_out[13]_output_0_0_to_lut_$abc$1686$abc$630$li14_li14_input_0_3  (
        .datain(\dffre_out[13]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li14_li14_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_out[13]_output_0_0_to_lut_$abc$1686$new_new_n64___input_0_4  (
        .datain(\dffre_out[13]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n64___input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_out[13]_output_0_0_to_out[13]_input_0_0  (
        .datain(\dffre_out[13]_output_0_0 ),
        .dataout(\out[13]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[14]_output_0_0_to_lut_$abc$1686$abc$630$li15_li15_input_0_4  (
        .datain(\dffre_out[14]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li15_li15_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_out[14]_output_0_0_to_lut_$abc$1686$abc$630$li13_li13_input_0_4  (
        .datain(\dffre_out[14]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li13_li13_input_0_4 )
    );

    fpga_interconnect \routing_segment_dffre_out[14]_output_0_0_to_lut_$abc$1686$new_new_n63___input_0_1  (
        .datain(\dffre_out[14]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n63___input_0_1 )
    );

    fpga_interconnect \routing_segment_dffre_out[14]_output_0_0_to_out[14]_input_0_0  (
        .datain(\dffre_out[14]_output_0_0 ),
        .dataout(\out[14]_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[15]_output_0_0_to_lut_$abc$1686$abc$630$li00_li00_input_0_3  (
        .datain(\dffre_out[15]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li00_li00_input_0_3 )
    );

    fpga_interconnect \routing_segment_dffre_out[15]_output_0_0_to_lut_$abc$1686$abc$630$li14_li14_input_0_0  (
        .datain(\dffre_out[15]_output_0_0 ),
        .dataout(\lut_$abc$1686$abc$630$li14_li14_input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[15]_output_0_0_to_lut_$abc$1686$new_new_n69___input_0_0  (
        .datain(\dffre_out[15]_output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n69___input_0_0 )
    );

    fpga_interconnect \routing_segment_dffre_out[15]_output_0_0_to_out[15]_input_0_0  (
        .datain(\dffre_out[15]_output_0_0 ),
        .dataout(\out[15]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[8]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[8]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[8]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[8]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[10]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[10]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[10]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[10]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[9]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[9]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[9]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[9]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[11]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[11]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[11]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[11]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[2]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[2]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[2]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[2]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[0]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[0]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[0]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[0]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[4]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[4]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[4]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[4]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[6]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[6]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[6]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[6]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[15]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[15]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[15]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[15]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[13]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[13]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[13]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[13]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[12]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[12]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[12]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[12]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[14]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[14]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[14]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[14]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[1]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[1]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[1]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[1]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[3]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[3]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[3]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[3]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[5]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[5]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[5]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[5]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[7]_input_1_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[7]_input_1_0 )
    );

    fpga_interconnect \routing_segment_lut_$true_output_0_0_to_dffre_out[7]_input_2_0  (
        .datain(\lut_$true_output_0_0 ),
        .dataout(\dffre_out[7]_input_2_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li12_li12_output_0_0_to_dffre_out[12]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li12_li12_output_0_0 ),
        .dataout(\dffre_out[12]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li07_li07_output_0_0_to_dffre_out[7]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li07_li07_output_0_0 ),
        .dataout(\dffre_out[7]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li09_li09_output_0_0_to_dffre_out[9]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li09_li09_output_0_0 ),
        .dataout(\dffre_out[9]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li14_li14_output_0_0_to_dffre_out[14]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li14_li14_output_0_0 ),
        .dataout(\dffre_out[14]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li15_li15_output_0_0_to_dffre_out[15]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li15_li15_output_0_0 ),
        .dataout(\dffre_out[15]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li05_li05_output_0_0_to_dffre_out[5]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li05_li05_output_0_0 ),
        .dataout(\dffre_out[5]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li03_li03_output_0_0_to_dffre_out[3]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li03_li03_output_0_0 ),
        .dataout(\dffre_out[3]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li01_li01_output_0_0_to_dffre_out[1]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li01_li01_output_0_0 ),
        .dataout(\dffre_out[1]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li00_li00_output_0_0_to_dffre_out[0]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li00_li00_output_0_0 ),
        .dataout(\dffre_out[0]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$new_new_n63___output_0_0_to_lut_$abc$1686$new_new_n64___input_0_3  (
        .datain(\lut_$abc$1686$new_new_n63___output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n64___input_0_3 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$new_new_n64___output_0_0_to_lut_loopback_error_input_0_1  (
        .datain(\lut_$abc$1686$new_new_n64___output_0_0 ),
        .dataout(\lut_loopback_error_input_0_1 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$new_new_n65___output_0_0_to_lut_$abc$1686$new_new_n66___input_0_0  (
        .datain(\lut_$abc$1686$new_new_n65___output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n66___input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$new_new_n66___output_0_0_to_lut_loopback_error_input_0_0  (
        .datain(\lut_$abc$1686$new_new_n66___output_0_0 ),
        .dataout(\lut_loopback_error_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$new_new_n67___output_0_0_to_lut_$abc$1686$new_new_n68___input_0_2  (
        .datain(\lut_$abc$1686$new_new_n67___output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n68___input_0_2 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$new_new_n68___output_0_0_to_lut_loopback_error_input_0_3  (
        .datain(\lut_$abc$1686$new_new_n68___output_0_0 ),
        .dataout(\lut_loopback_error_input_0_3 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$new_new_n69___output_0_0_to_lut_$abc$1686$new_new_n70___input_0_4  (
        .datain(\lut_$abc$1686$new_new_n69___output_0_0 ),
        .dataout(\lut_$abc$1686$new_new_n70___input_0_4 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$new_new_n70___output_0_0_to_lut_loopback_error_input_0_4  (
        .datain(\lut_$abc$1686$new_new_n70___output_0_0 ),
        .dataout(\lut_loopback_error_input_0_4 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li02_li02_output_0_0_to_dffre_out[2]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li02_li02_output_0_0 ),
        .dataout(\dffre_out[2]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li04_li04_output_0_0_to_dffre_out[4]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li04_li04_output_0_0 ),
        .dataout(\dffre_out[4]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li06_li06_output_0_0_to_dffre_out[6]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li06_li06_output_0_0 ),
        .dataout(\dffre_out[6]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li13_li13_output_0_0_to_dffre_out[13]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li13_li13_output_0_0 ),
        .dataout(\dffre_out[13]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li10_li10_output_0_0_to_dffre_out[10]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li10_li10_output_0_0 ),
        .dataout(\dffre_out[10]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li11_li11_output_0_0_to_dffre_out[11]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li11_li11_output_0_0 ),
        .dataout(\dffre_out[11]_input_0_0 )
    );

    fpga_interconnect \routing_segment_lut_$abc$1686$abc$630$li08_li08_output_0_0_to_dffre_out[8]_input_0_0  (
        .datain(\lut_$abc$1686$abc$630$li08_li08_output_0_0 ),
        .dataout(\dffre_out[8]_input_0_0 )
    );


    //Cell instances
    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000011000000100000000000000010)
    ) \lut_$abc$1686$abc$630$li08_li08  (
        .in({
            \lut_$abc$1686$abc$630$li08_li08_input_0_4 ,
            \lut_$abc$1686$abc$630$li08_li08_input_0_3 ,
            \lut_$abc$1686$abc$630$li08_li08_input_0_2 ,
            1'b0,
            \lut_$abc$1686$abc$630$li08_li08_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li08_li08_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[8]  (
        .C(\dffre_out[8]_clock_0_0 ),
        .D(\dffre_out[8]_input_0_0 ),
        .E(\dffre_out[8]_input_2_0 ),
        .R(\dffre_out[8]_input_1_0 ),
        .Q(\dffre_out[8]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000101000001100)
    ) \lut_$abc$1686$abc$630$li10_li10  (
        .in({
            1'b0,
            \lut_$abc$1686$abc$630$li10_li10_input_0_3 ,
            \lut_$abc$1686$abc$630$li10_li10_input_0_2 ,
            \lut_$abc$1686$abc$630$li10_li10_input_0_1 ,
            \lut_$abc$1686$abc$630$li10_li10_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li10_li10_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[10]  (
        .C(\dffre_out[10]_clock_0_0 ),
        .D(\dffre_out[10]_input_0_0 ),
        .E(\dffre_out[10]_input_2_0 ),
        .R(\dffre_out[10]_input_1_0 ),
        .Q(\dffre_out[10]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000011100010)
    ) \lut_$abc$1686$abc$630$li09_li09  (
        .in({
            \lut_$abc$1686$abc$630$li09_li09_input_0_4 ,
            1'b0,
            \lut_$abc$1686$abc$630$li09_li09_input_0_2 ,
            \lut_$abc$1686$abc$630$li09_li09_input_0_1 ,
            \lut_$abc$1686$abc$630$li09_li09_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li09_li09_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[9]  (
        .C(\dffre_out[9]_clock_0_0 ),
        .D(\dffre_out[9]_input_0_0 ),
        .E(\dffre_out[9]_input_2_0 ),
        .R(\dffre_out[9]_input_1_0 ),
        .Q(\dffre_out[9]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000101100001000)
    ) \lut_$abc$1686$abc$630$li11_li11  (
        .in({
            \lut_$abc$1686$abc$630$li11_li11_input_0_4 ,
            \lut_$abc$1686$abc$630$li11_li11_input_0_3 ,
            1'b0,
            \lut_$abc$1686$abc$630$li11_li11_input_0_1 ,
            \lut_$abc$1686$abc$630$li11_li11_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li11_li11_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[11]  (
        .C(\dffre_out[11]_clock_0_0 ),
        .D(\dffre_out[11]_input_0_0 ),
        .E(\dffre_out[11]_input_2_0 ),
        .R(\dffre_out[11]_input_1_0 ),
        .Q(\dffre_out[11]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000001100100000000000010000)
    ) \lut_$abc$1686$abc$630$li02_li02  (
        .in({
            \lut_$abc$1686$abc$630$li02_li02_input_0_4 ,
            1'b0,
            \lut_$abc$1686$abc$630$li02_li02_input_0_2 ,
            \lut_$abc$1686$abc$630$li02_li02_input_0_1 ,
            \lut_$abc$1686$abc$630$li02_li02_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li02_li02_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[2]  (
        .C(\dffre_out[2]_clock_0_0 ),
        .D(\dffre_out[2]_input_0_0 ),
        .E(\dffre_out[2]_input_2_0 ),
        .R(\dffre_out[2]_input_1_0 ),
        .Q(\dffre_out[2]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000011000000010000001000000000)
    ) \lut_$abc$1686$abc$630$li00_li00  (
        .in({
            \lut_$abc$1686$abc$630$li00_li00_input_0_4 ,
            \lut_$abc$1686$abc$630$li00_li00_input_0_3 ,
            1'b0,
            \lut_$abc$1686$abc$630$li00_li00_input_0_1 ,
            \lut_$abc$1686$abc$630$li00_li00_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li00_li00_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[0]  (
        .C(\dffre_out[0]_clock_0_0 ),
        .D(\dffre_out[0]_input_0_0 ),
        .E(\dffre_out[0]_input_2_0 ),
        .R(\dffre_out[0]_input_1_0 ),
        .Q(\dffre_out[0]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000011000000100000000000000010)
    ) \lut_$abc$1686$abc$630$li04_li04  (
        .in({
            \lut_$abc$1686$abc$630$li04_li04_input_0_4 ,
            \lut_$abc$1686$abc$630$li04_li04_input_0_3 ,
            1'b0,
            \lut_$abc$1686$abc$630$li04_li04_input_0_1 ,
            \lut_$abc$1686$abc$630$li04_li04_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li04_li04_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[4]  (
        .C(\dffre_out[4]_clock_0_0 ),
        .D(\dffre_out[4]_input_0_0 ),
        .E(\dffre_out[4]_input_2_0 ),
        .R(\dffre_out[4]_input_1_0 ),
        .Q(\dffre_out[4]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000010001000110000)
    ) \lut_$abc$1686$abc$630$li06_li06  (
        .in({
            1'b0,
            \lut_$abc$1686$abc$630$li06_li06_input_0_3 ,
            \lut_$abc$1686$abc$630$li06_li06_input_0_2 ,
            \lut_$abc$1686$abc$630$li06_li06_input_0_1 ,
            \lut_$abc$1686$abc$630$li06_li06_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li06_li06_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[6]  (
        .C(\dffre_out[6]_clock_0_0 ),
        .D(\dffre_out[6]_input_0_0 ),
        .E(\dffre_out[6]_input_2_0 ),
        .R(\dffre_out[6]_input_1_0 ),
        .Q(\dffre_out[6]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000111111100000000011110100)
    ) \lut_$abc$1686$abc$630$li15_li15  (
        .in({
            \lut_$abc$1686$abc$630$li15_li15_input_0_4 ,
            1'b0,
            \lut_$abc$1686$abc$630$li15_li15_input_0_2 ,
            \lut_$abc$1686$abc$630$li15_li15_input_0_1 ,
            \lut_$abc$1686$abc$630$li15_li15_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li15_li15_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[15]  (
        .C(\dffre_out[15]_clock_0_0 ),
        .D(\dffre_out[15]_input_0_0 ),
        .E(\dffre_out[15]_input_2_0 ),
        .R(\dffre_out[15]_input_1_0 ),
        .Q(\dffre_out[15]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000011000000010000001000000000)
    ) \lut_$abc$1686$abc$630$li13_li13  (
        .in({
            \lut_$abc$1686$abc$630$li13_li13_input_0_4 ,
            \lut_$abc$1686$abc$630$li13_li13_input_0_3 ,
            \lut_$abc$1686$abc$630$li13_li13_input_0_2 ,
            1'b0,
            \lut_$abc$1686$abc$630$li13_li13_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li13_li13_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[13]  (
        .C(\dffre_out[13]_clock_0_0 ),
        .D(\dffre_out[13]_input_0_0 ),
        .E(\dffre_out[13]_input_2_0 ),
        .R(\dffre_out[13]_input_1_0 ),
        .Q(\dffre_out[13]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000100010101000000)
    ) \lut_$abc$1686$abc$630$li12_li12  (
        .in({
            \lut_$abc$1686$abc$630$li12_li12_input_0_4 ,
            \lut_$abc$1686$abc$630$li12_li12_input_0_3 ,
            \lut_$abc$1686$abc$630$li12_li12_input_0_2 ,
            \lut_$abc$1686$abc$630$li12_li12_input_0_1 ,
            1'b0
         }),
        .out(\lut_$abc$1686$abc$630$li12_li12_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[12]  (
        .C(\dffre_out[12]_clock_0_0 ),
        .D(\dffre_out[12]_input_0_0 ),
        .E(\dffre_out[12]_input_2_0 ),
        .R(\dffre_out[12]_input_1_0 ),
        .Q(\dffre_out[12]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000011001000000010)
    ) \lut_$abc$1686$abc$630$li14_li14  (
        .in({
            \lut_$abc$1686$abc$630$li14_li14_input_0_4 ,
            \lut_$abc$1686$abc$630$li14_li14_input_0_3 ,
            \lut_$abc$1686$abc$630$li14_li14_input_0_2 ,
            1'b0,
            \lut_$abc$1686$abc$630$li14_li14_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li14_li14_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[14]  (
        .C(\dffre_out[14]_clock_0_0 ),
        .D(\dffre_out[14]_input_0_0 ),
        .E(\dffre_out[14]_input_2_0 ),
        .R(\dffre_out[14]_input_1_0 ),
        .Q(\dffre_out[14]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000011100000000000000100)
    ) \lut_$abc$1686$abc$630$li01_li01  (
        .in({
            \lut_$abc$1686$abc$630$li01_li01_input_0_4 ,
            \lut_$abc$1686$abc$630$li01_li01_input_0_3 ,
            1'b0,
            \lut_$abc$1686$abc$630$li01_li01_input_0_1 ,
            \lut_$abc$1686$abc$630$li01_li01_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li01_li01_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[1]  (
        .C(\dffre_out[1]_clock_0_0 ),
        .D(\dffre_out[1]_input_0_0 ),
        .E(\dffre_out[1]_input_2_0 ),
        .R(\dffre_out[1]_input_1_0 ),
        .Q(\dffre_out[1]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000011011000)
    ) \lut_$abc$1686$abc$630$li03_li03  (
        .in({
            1'b0,
            \lut_$abc$1686$abc$630$li03_li03_input_0_3 ,
            \lut_$abc$1686$abc$630$li03_li03_input_0_2 ,
            \lut_$abc$1686$abc$630$li03_li03_input_0_1 ,
            \lut_$abc$1686$abc$630$li03_li03_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li03_li03_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[3]  (
        .C(\dffre_out[3]_clock_0_0 ),
        .D(\dffre_out[3]_input_0_0 ),
        .E(\dffre_out[3]_input_2_0 ),
        .R(\dffre_out[3]_input_1_0 ),
        .Q(\dffre_out[3]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000101010000010000)
    ) \lut_$abc$1686$abc$630$li05_li05  (
        .in({
            \lut_$abc$1686$abc$630$li05_li05_input_0_4 ,
            \lut_$abc$1686$abc$630$li05_li05_input_0_3 ,
            \lut_$abc$1686$abc$630$li05_li05_input_0_2 ,
            \lut_$abc$1686$abc$630$li05_li05_input_0_1 ,
            1'b0
         }),
        .out(\lut_$abc$1686$abc$630$li05_li05_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[5]  (
        .C(\dffre_out[5]_clock_0_0 ),
        .D(\dffre_out[5]_input_0_0 ),
        .E(\dffre_out[5]_input_2_0 ),
        .R(\dffre_out[5]_input_1_0 ),
        .Q(\dffre_out[5]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000011100010)
    ) \lut_$abc$1686$abc$630$li07_li07  (
        .in({
            \lut_$abc$1686$abc$630$li07_li07_input_0_4 ,
            1'b0,
            \lut_$abc$1686$abc$630$li07_li07_input_0_2 ,
            \lut_$abc$1686$abc$630$li07_li07_input_0_1 ,
            \lut_$abc$1686$abc$630$li07_li07_input_0_0 
         }),
        .out(\lut_$abc$1686$abc$630$li07_li07_output_0_0 )
    );

    DFFRE #(
    ) \dffre_out[7]  (
        .C(\dffre_out[7]_clock_0_0 ),
        .D(\dffre_out[7]_input_0_0 ),
        .E(\dffre_out[7]_input_2_0 ),
        .R(\dffre_out[7]_input_1_0 ),
        .Q(\dffre_out[7]_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b10000010000000000000000010000010)
    ) \lut_$abc$1686$new_new_n66__  (
        .in({
            \lut_$abc$1686$new_new_n66___input_0_4 ,
            \lut_$abc$1686$new_new_n66___input_0_3 ,
            \lut_$abc$1686$new_new_n66___input_0_2 ,
            \lut_$abc$1686$new_new_n66___input_0_1 ,
            \lut_$abc$1686$new_new_n66___input_0_0 
         }),
        .out(\lut_$abc$1686$new_new_n66___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b10010000000000000000000010010000)
    ) \lut_$abc$1686$new_new_n68__  (
        .in({
            \lut_$abc$1686$new_new_n68___input_0_4 ,
            \lut_$abc$1686$new_new_n68___input_0_3 ,
            \lut_$abc$1686$new_new_n68___input_0_2 ,
            \lut_$abc$1686$new_new_n68___input_0_1 ,
            \lut_$abc$1686$new_new_n68___input_0_0 
         }),
        .out(\lut_$abc$1686$new_new_n68___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b10010000000000000000100100000000)
    ) \lut_$abc$1686$new_new_n64__  (
        .in({
            \lut_$abc$1686$new_new_n64___input_0_4 ,
            \lut_$abc$1686$new_new_n64___input_0_3 ,
            \lut_$abc$1686$new_new_n64___input_0_2 ,
            \lut_$abc$1686$new_new_n64___input_0_1 ,
            \lut_$abc$1686$new_new_n64___input_0_0 
         }),
        .out(\lut_$abc$1686$new_new_n64___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01000000000001000001000000000001)
    ) \lut_$abc$1686$new_new_n67__  (
        .in({
            \lut_$abc$1686$new_new_n67___input_0_4 ,
            \lut_$abc$1686$new_new_n67___input_0_3 ,
            \lut_$abc$1686$new_new_n67___input_0_2 ,
            \lut_$abc$1686$new_new_n67___input_0_1 ,
            1'b0
         }),
        .out(\lut_$abc$1686$new_new_n67___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01110000111100001111000011110000)
    ) \lut_loopback_error  (
        .in({
            \lut_loopback_error_input_0_4 ,
            \lut_loopback_error_input_0_3 ,
            \lut_loopback_error_input_0_2 ,
            \lut_loopback_error_input_0_1 ,
            \lut_loopback_error_input_0_0 
         }),
        .out(\lut_loopback_error_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b01000000000100000000010000000001)
    ) \lut_$abc$1686$new_new_n63__  (
        .in({
            \lut_$abc$1686$new_new_n63___input_0_4 ,
            \lut_$abc$1686$new_new_n63___input_0_3 ,
            \lut_$abc$1686$new_new_n63___input_0_2 ,
            \lut_$abc$1686$new_new_n63___input_0_1 ,
            1'b0
         }),
        .out(\lut_$abc$1686$new_new_n63___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b10000100001000010000000000000000)
    ) \lut_$abc$1686$new_new_n70__  (
        .in({
            \lut_$abc$1686$new_new_n70___input_0_4 ,
            \lut_$abc$1686$new_new_n70___input_0_3 ,
            \lut_$abc$1686$new_new_n70___input_0_2 ,
            \lut_$abc$1686$new_new_n70___input_0_1 ,
            \lut_$abc$1686$new_new_n70___input_0_0 
         }),
        .out(\lut_$abc$1686$new_new_n70___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00001001000000000000000000001001)
    ) \lut_$abc$1686$new_new_n69__  (
        .in({
            \lut_$abc$1686$new_new_n69___input_0_4 ,
            \lut_$abc$1686$new_new_n69___input_0_3 ,
            1'b0,
            \lut_$abc$1686$new_new_n69___input_0_1 ,
            \lut_$abc$1686$new_new_n69___input_0_0 
         }),
        .out(\lut_$abc$1686$new_new_n69___output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000000000000000000000000001)
    ) \lut_$true  (
        .in({
            1'b0,
            1'b0,
            1'b0,
            1'b0,
            1'b0
         }),
        .out(\lut_$true_output_0_0 )
    );

    LUT_K #(
        .K(5),
        .LUT_MASK(32'b00000000100001000000000000100001)
    ) \lut_$abc$1686$new_new_n65__  (
        .in({
            \lut_$abc$1686$new_new_n65___input_0_4 ,
            1'b0,
            \lut_$abc$1686$new_new_n65___input_0_2 ,
            \lut_$abc$1686$new_new_n65___input_0_1 ,
            \lut_$abc$1686$new_new_n65___input_0_0 
         }),
        .out(\lut_$abc$1686$new_new_n65___output_0_0 )
    );


endmodule
