create_design signed_accum_output_shifted_saturated_overflow_underflow_inst
target_device GEMINI_COMPACT_82x68
add_include_path ./rtl
add_library_path ./rtl
add_library_ext .v .sv
add_design_file ./rtl/signed_accum_output_shifted_saturated_overflow_underflow_inst.v
set_top_module signed_accum_output_shifted_saturated_overflow_underflow_inst
analyze
synthesize delay
