-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/02_17_2023_10_33_43/share/raptor/sim_models/rapidsilicon/genesis2/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir ../. /nfs_project/castor/DV/Hamza/RS/Jira_Testcase/CASTORIP-160 
-vlog-libdir 
-vlog-define 
-vlog2k /nfs_project/castor/DV/Hamza/RS/Jira_Testcase/CASTORIP-160/and2.v
-top and2
