create_design clk_buf_ff
add_design_file clk_buf_ff.v
set_top_module clk_buf_ff
add_constraint_file constraints.sdc
add_constraint_file pin_constraints.pin
target_device 1VG28

analyze
synthesize
packing
place
route
sta
bitstream