-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/06_11_2023_09_15_01/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir ../ /nfs_project/gemini/DV/usmanqadir/jira_repo/Jira_Testcase/RIGELIP-17/ram_inst_sp_36/. 
-vlog-libdir 
-vlog-define 
-vlog2k /nfs_project/gemini/DV/usmanqadir/jira_repo/Jira_Testcase/RIGELIP-17/ram_inst_sp_36/./ram_inst_sp_36.v
-top ram_inst_sp_36
