-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/08_30_2023_09_15_01/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir ../../../../ /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/async_counter/Jira/./rtl 
-vhdl2019 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/async_counter/Jira/./rtl/top.vhd
-top top
