-sv2009 /nfs_eda_sw/softwares/Raptor/instl_dir/08_30_2023_09_15_01/share/raptor/sim_models/rapidsilicon/genesis3/cell_sim_blackbox.v
-set-warning VERI-1063
-vlog-incdir ../../../../ /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/fpu_double/jira/./rtl 
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/fpu_double/jira/./rtl/fpupack.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/fpu_double/jira/./rtl/comppack.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/fpu_double/jira/./rtl/fpu_add.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/fpu_double/jira/./rtl/fpu_mul.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/fpu_double/jira/./rtl/fpu_exceptions.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/fpu_double/jira/./rtl/fpu_round.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/fpu_double/jira/./rtl/fpu_sub.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/fpu_double/jira/./rtl/fpu_div.vhd
-vhdl2008 /nfs_scratch/scratch/CompilerValidation/zaheer_ahmad/Compiler_Validation/RTL_testcases/GHDL_testcases/fpu_double/jira/./rtl/fpu_double.vhd
-top fpu_double
