read_verilog -sv /nfs_eda_sw/softwares/Raptor/instl_dir/04_26_2024_09_15_01/share/raptor/sim_models/rapidsilicon/genesis3/FPGA_PRIMITIVES_MODELS/blackbox_models/cell_sim_blackbox.v
plugin -i systemverilog
read_systemverilog -synth  -top aes -y ../../../.././rtl -I../../../.././rtl -I../../../../ -I/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl +libext+.v+.sv -sv /nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_util_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_reg_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_mubi_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/top_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_secded_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/tlul_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_alert_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_subreg_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_sbox_canright_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/lc_ctrl_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/entropy_src_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/edn_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/keymgr_reg_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/keymgr_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_pkg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_cipher_control.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_cipher_control_fsm.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_cipher_control_fsm_n.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_cipher_control_fsm_p.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_cipher_core.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_control.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_control_fsm.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_control_fsm_n.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_control_fsm_p.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_core.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_ctr.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_ctr_fsm.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_ctr_fsm_n.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_ctr_fsm_p.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_ctrl_reg_shadowed.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_key_expand.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_mix_columns.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_mix_single_column.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_prng_clearing.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_prng_masking.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_reg_status.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_reg_top.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_sbox.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_sbox_canright.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_sbox_canright_masked.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_sbox_canright_masked_noreuse.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_sbox_lut.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_sel_buf_chk.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_shift_rows.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_sub_bytes.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/aes_sbox_dom.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_alert_sender.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_buf.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_diff_decode.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_flop.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_flop_2sync.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_generic_buf.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_generic_flop.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_generic_flop_2sync.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_generic_xor2.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_lc_sync.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_lfsr.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_flop_en.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_secded_inv_39_32_dec.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_secded_inv_39_32_enc.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_secded_inv_64_57_dec.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_secded_inv_64_57_enc.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_sparse_fsm_flop.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_subreg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_subreg_arb.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_subreg_ext.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_subreg_shadow.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_sync_reqack.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_sync_reqack_data.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_generic_flop_en.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/prim_xor2.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/tlul_adapter_reg.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/tlul_cmd_intg_chk.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/tlul_data_integ_dec.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/tlul_data_integ_enc.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/tlul_err.sv \
/nfs_scratch/scratch/CompilerValidation/abdul_hameed/24apr/Jira_Testcase/EDA-2753/aes/./rtl/tlul_rsp_intg_gen.sv \

analyze -top aes
